README.md
doc/vital-assertion.txt
doc/vital-data-lazylist.txt
doc/vital-interpreter-brainf__k.txt
doc/vital-text-lexer.txt
doc/vital-text-parser.txt
doc/vital-vim-search.txt
doc/vital.txt

短期間に何度も Pull Request 出して申し訳ないですが、
よろしくお願いします。

Improve document

---

autoload/vital/__latest__/Text/TOML.vim
doc/vital-text-toml.txt
test/Text/TOML.vim
test/Text/toml-sample.txt

lingrで話していたtoml用のパーサをvital用にブラッシュアップしました。

Text.TOML: Add a new module `Text.TOML'.

---

autoload/vital/__latest__/Math.vim
doc/vital-math.txt
test/Math.vimspec

I implemented simply function 'sum',
Please merge this.

Math: Added the function 'sum'

---

autoload/vital/__latest__/Data/String.vim
autoload/vital/__latest__/System/Cache.vim
doc/vital-data-string.txt
test/Data/String.vim

http://lingr.com/room/vim/archives/2015/02/09
see also: https://github.com/ynkdir/vim-funlib/blob/master/autoload/hashlib/sha256.vim

Data.String: add hash()

---

autoload/vital/__latest__/Data/List.vim
doc/vital-data-list.txt
spec/data/list.vim

has_common_items()はあるのに要素返すものがなかったので足しました。

Data.List: Add intersect().

---

README.md
autoload/vital/__latest__/Data/Optional.vim
doc/vital-data-optional.txt
doc/vital.txt
test/Data/Optional.vimspec

このプルリクエストは未完成です．意見を聞きたいので先にプルリクしました．
このプルリクでは `Data.Option` コンテナを実装しています．
これはいわゆる Haskell でいう `Maybe` や Scala でいう `Option`，C++ でいう `std::optional` のような，無効値になりうるコンテナです．
例で見たほうが分かりやすいと思うので：
```vim
let s:V = vital#of('vital')
let s:O = s:V.import('Data.Option')
function! GetSecretFile()
let path = expand('~/.secret')
if filereadable(path)
return s:O.some(readfile(path))
else
return s:O.none()
endif
endfunction
let maybe_file = GetSecretFile()
" 1. File was found?
if s:O.empty(maybe_file)
echomsg "Not found!"
endif
" 2. Get the file content or create new content
let content = s:O.get_or(maybe_file, ['sercret number : '])
echo content
" 3. Apply function to the optional value
function! s:add_new_line(content)
return a:content + ['this is new line']
endfunction
let result = …
```

Added Data.Optional

---

autoload/vital/__latest__/Data/Tree.vim
doc/vital-data-tree.txt

#236 の件、実装してみたのでとりあえずpull requestします。

Data.Tree: improve renderer()

---

autoload/vital/__latest__/DateTime.vim
doc/vital-date_time.txt
test/DateTime.vimspec

DateTime 色々直し

---

doc/vital-text-sexp.txt

Text.Sexp: documentation (refs #279)

---

test/.themisrc
test/README.md

vital.vim に修正を送りたい人が皆 themis.vim に詳しいわけではないと思うので，テストの実行方法についての README 書いてみました．
特に気になっていてレビューしてほしいのは下記の点です．
- doc/vital.txt の中のほうが良い？（Vim プラグイン的には help 内のほうが良い気もしますが，vital 本体の開発の話ですし README のほうが良い気も）
- 「とりあえず themis.vim 使ってテストを実行する」程度の場合，この README 内のやり方で妥当？

Added README for running test

---

README.md
doc/vital.txt

Text.Sexp: Add links

---

autoload/vital/__latest__/Data/String.vim

Data.String: Fix Prelude.wcswidth is deprecated exception in wrap

---

.travis.yml
install-vim.sh

http://docs.travis-ci.com/user/migrating-from-legacy/
テスト自体は数分の短縮ですが、立ち上がりがすごく早いです。

Migrate to container-based infrastructure on Travis CI

---

autoload/vitalizer.vim

Vitalizer: Changes show module names

---

autoload/vital/__latest__/Web/HTTP.vim
doc/vital-web-http.txt

いろいろ手直ししましたが、大きいのは、
- レスポンスにリダイレクトの情報も含めるようにした。
- python クライアントで `maxRedirect` に対応した。
の2点です。一応 PR で出しましたが特に意見なければサクッとマージ予定。

Web.HTTP いろいろ改良

---

autoload/vital/__latest__/Data/String.vim
doc/vital-data-string.txt
test/Data/String.vim

References for method name
- https://msdn.microsoft.com/en-us/library/system.string.trimstart(v=vs.110).aspx
- https://msdn.microsoft.com/en-us/library/system.string.trimend(v=vs.110).aspx
I also added spec for `Data.String.trim()`

Implement Data.String.trim_start(), Data.String.trim_end()

---

autoload/vital/__latest__/Math.vim
doc/vital-math.txt
test/Math.vim

Mathにstr2nr, nr2strを追加しました。
2進数から36進数までの基数変換を行います。

Math: add str2nr(), nr2str()

---

README.md

add "Plugins Using vital.vim"

---

autoload/vital/__latest__/DateTime.vim
test/DateTime.vimspec

#334 を直すついでにちょろちょろっとあちこち直しました。

DateTime あれこれ直し

---

appveyor.yml
autoload/vital/__latest__/DateTime.vim
autoload/vital/__latest__/Interpreter/Brainf__k.vim
autoload/vital/__latest__/Text/Sexp.vim
autoload/vital/__latest__/Vim/ScriptLocal.vim
test/.themisrc
test/ConcurrentProcess.vim
test/Vim/ScriptLocal.vimspec

Windows で動いていなかったいくつかのモジュールの実装およびテストを修正しているので、メンテナの @ujihisa さんと @haya14busa さんは確認してもらえると助かります。

AppVeyor 対応

---

autoload/vital/__latest__/System/Filepath.vim
doc/vital-system-filepath.txt
test/System/Filepath.vimspec

System.Filepath: Add path management functions

---

autoload/vital/__latest__/Lua/Prelude.vim
autoload/vital/__latest__/Text/Sexp.vim
autoload/vitalizer.vim

ref: #60
Add a file path that starts with "." to a list in "_vital_depends()" to
include the data file.

vitalizer: Add ability to include data files

---

autoload/vital/__latest__/System/Filepath.vim
doc/vital-system-filepath.txt
test/System/Filepath.vimspec

The function that I've mentioned in Lingr Vim room long ago. I've fixed Windows tests and amended.
This function is based on neoclojure's internal util one.

System.Filepath: Add is_root_directory()

---

autoload/vital/__latest__/Vim/Compat.vim
doc/vital-vim-compat.txt
test/Vim/Compat.vimspec

https://github.com/vim-jp/vital.vim/issues/343

Vim.Compat: Add several compatible functions

---

autoload/vital/__latest__/Process.vim
doc/vital-process.txt

* It's one of a TODO described at the top of process.vim

Process: Convert comment to doc

---

autoload/vital/__latest__/Web/URI.vim
test/Web/URI.vimspec

Web.URI: does not allow some uri

---

autoload/vital/__latest__.vim

`s:_vital_loaded()`で例外が吐かれても該当モジュールがキャッシュされてしまうので修正
#370 を試しているときに気づきましたが，直接は関係なさそうなのでﾌﾟﾙﾘ
ref: https://github.com/vim-jp/vital.vim/pull/370#issuecomment-175712399
1. vital を #370 branch に
2. vital-powerassertリポジトリ(任意の別のモジュールに依存している外部モジュール)に移動
3. `:Vitalize . --name=powerassert`
4. 自分自身を import (以下のscriptを`:source`) -> `s:vital_loaded()`からエラー (expected)
5. もっかい `:source`
- expect: `_vital_loaded` からエラー
- actual: `_vital_loaded` が呼ばれず無言. なお実際にモジュールを使おうとすると`s:_vital_loaded()`が呼ばれてないせいでその時点でエラー
```vim
let s:V = vital#of('powerassert')
let s:PowerAssert = s:V.import('Vim.PowerAssert')
```
#370を使わなくても`:Vitaliz`時にエラーを吐かないようにして，`import` 時に`_vital_loaded()`からエラー吐かせることで再現可能なハズ
```
Error detected while processing function <SNR>571_import[11]..<SNR>571__import[20]..<SNR>571__build_module[18]..<SNR>57 …
```

Remove module cache if error occurs from module._vital_loaded

---

autoload/vitalizer.vim

Fix vitalizer (#389)

---

autoload/vital/__latest__/System/Filepath.vim
doc/vital-system-filepath.txt
test/System/Filepath.vimspec

先日 `System.Filepath` をいじってて気になった部分の修正。
本当はテストもちゃんと追加したい…。

System.Filepath: some improves

---

README.md

Add "Powered by vital.vim" badge to README

---

autoload/vital/__latest__.vim
autoload/vitalizer.vim

Loading may fail when there is two or more vitalized plugin to same place.
Thanks @ichizok for reporting this!

Fix vital loader

---

autoload/vital/__latest__/System/File.vim
doc/vital-system-file.txt

NOTE: `s:copy_dir_exe()` is not supported on Windows

System.File: Add copy_dir()

---

appveyor.yml

add appveyor notification

---

.travis.yml

Add same config for travis ci corresponding to appveyor's one. ref: #427

.travis.yml: set clone-depth option which correspond to #427

---

.travis.yml
appveyor.yml
autoload/vital/__vital__/System/Filepath.vim
autoload/vital/__vital__/Vim/Guard.vim
scripts/install-vim.sh
test/System/Filepath.vimspec
test/Vim/Guard.vimspec

#451 の対応です。
テストうまく回るか試さないとわからないので、うまくいかなかった場合 push -f で試行錯誤予定です。

Update CI envs

---

doc/vital.txt
doc/vital/Data/BigNum.txt
doc/vital/Data/LazyList.txt

Fix hyperlink in README

---

doc/vital.txt

Fix broken tag links

---

autoload/vital/__vital__/Data/List.vim
doc/vital/Data/List.txt
test/Data/List.vimspec

Data.List: Add 'drop_while' function.

---

autoload/vital/__vital__/DateTime.vim

DateTime: Add a missing dependency

---

test/Vim/Message.vimspec

Vim.Message: fix test after Vim 8.0.0467

---

test/Locale/Message.vimspec
test/README.md

* Style document
* Locale.Message: Fix tests for environments which dont have ja_JP.UTF-8 locale

Trivial tweaks

---

README.md
doc/vital.txt

Remove ProcessManager from generic vital docs

---

autoload/vital/__vital__/Data/Optional.vim
doc/vital/Data/Optional.txt
test/Data/Optional.vimspec

For simple API 🤔  
(I think 'map' is most popular name 😄 )

Data.Optional: Add .map()

---

autoload/vital/__vital__/Stream.vim
doc/vital/Stream.txt
test/Stream.vimspec

Previous PR (#498) has been too complicated because of lots of comments.
so I newly created this PR.

Stream (ver.2)

---

README.md

- Found Stream is not listed in README
- Made the list in alphabetical order
- Fixed unescaped `[`

Update modules list in README

---

doc/vital/Data/Closure.txt

Data.Closure: Fix a helptag

---

doc/vital/Stream.txt

Stream モジュールのドキュメントについて，以下の2点を変更しました．
- コード例中の string expressions をラムダ式に
- `drop_while()` 関数の出力例の誤りを修正

Stream: fix doc

---

doc/vital/Stream.txt

Stream: fix doc indent

---

doc/vital/Web/URI.txt

Web.URI: doc: Fix example

---

autoload/vital/__vital__/Data/Optional.vim
doc/vital/Data/Optional.txt
test/Data/Optional.vimspec

pullreqなげた今のタイミングではまだ実装ないです。まずインタフェースについて。
Data.Optionalに、nullつぽい値ならnoneでそうじゃなくて値っぽいのがあればsomeを返すやつがあると実用上めっちゃ便利なので、それを追加したいなーというpullreqです。
この方針でよさそうならこっちでテストと実装かけますー。
ちなみにこれはscalaにあって、あっちだと `val o = Option(x)` みたいに書きます。xがnullのときはNoneに、そうでないときはSomeになる感じ。内部的にはOption.applyメソッドが呼ばれてる、と。Vimの場合はnewとかがいいかなーと。利用を推奨していく感じなので

Data.Optional.new

---

autoload/vital/__vital__/Process.vim

discovered via https://github.com/tyru/open-browser.vim/pull/98

Process: wrap str as string

---

autoload/vital/__vital__/Vim/Type.vim
doc/vital/Vim/Type.txt
test/Vim/Type.vimspec

This is useful when user want to compare any two values.

Vim.Type: Add is_comparable() function

---

README.md

Add paragraphs to describe what vital.vim solves

---

README.md

add 3 missing modules into README

Trivial README fixes #583

---

autoload/vital/__vital__/Vim/Search.vim

It has been TODO for 4 to 5 years. Now it's time to resolve! https://github.com/vim-jp/vital.vim/blame/master/autoload/vital/__vital__/Vim/Search.vim#L50

Vim.Search: Refactor to resolve a TODO

---

autoload/vital/__vital__/DateTime.vim
autoload/vital/__vital__/Prelude.vim
autoload/vital/__vital__/Process.vim
autoload/vital/__vital__/System/File.vim
autoload/vital/__vital__/Vim/Compat.vim
test/.themisrc
test/Prelude.vimspec
test/Process.vimspec
test/System/Filepath.vimspec
test/Vim/Guard.vimspec

This is derived from https://github.com/vim-jp/vital.vim/pull/589#issuecomment-396501876

Simplyfy windows detection

---

Changes

via https://github.com/vim-jp/vital.vim/issues/588#issuecomment-396923361
Fix #588

Update changes (#591, #582)

---

autoload/vital/__vital__/Vim/Python.vim

https://github.com/vim-jp/issues/issues/1175

Vim.Python: Fix DeprecationWarning issue on Py 3.7

---

test/Data/List.vimspec

#597 
This PR confirms clarifications added by #597 
* checking non-destructive functions are non-destructive
* checking destructive functions are destructive

Data.List: Add List destructive/non-destructive functions tests

---

doc/vital/Web/HTTP.txt

https://github.com/vim-jp/vital.vim/pull/599

Web.HTTP: More documented

---

README.md

before:
This pullreq will show this like https://github.com/vim-jp/vital.vim/graphs/contributors

README: Reorder top contributors

---

autoload/vital/__vital__/Data/Either.vim
doc/vital/Data/Either.txt
test/Data/Either.vimspec

こうやって便利 :smile: 
```vim
call s:Either.bimap(s:成功メッセージもしくは失敗メッセージをEitherで返すやつ(),
\ { msg -> s:Msg.echo('None', msg) },
\ { msg -> s:Msg.echo('Error', msg) }
\ )
```
if-elseif と Either.is_left, is_rightであれこれするよりもとっても楽 :eyes:

Add .bimap function to Data.Either

---

doc/vital/Data/List.txt

Data.List: Add a needed space to the document

---

.appveyor.yml
.travis.yml
README.md
autoload/vital/__vital__/Data/Closure.vim
autoload/vital/__vital__/Data/String.vim
autoload/vital/__vital__/Prelude.vim
autoload/vital/__vital__/Process.vim
autoload/vital/__vital__/System/File.vim
autoload/vital/__vital__/System/Process/System.vim
autoload/vital/__vital__/Vim/Guard.vim
autoload/vital/__vital__/Vim/Python.vim
autoload/vital/__vital__/Vim/ViewTracer.vim
autoload/vital/vital.vim
doc/vital.txt
doc/vital/Vim/ViewTracer.txt
test/Data/Either.vimspec
test/Data/List.vimspec
test/Data/String.vim
test/Vim/Guard.vimspec
test/Vim/Python.vimspec
test/Vim/ViewTracer.vimspec
test/vital.vimspec

Drop Vim 7.4 support

---

autoload/vital/__vital__/Data/Optional.vim
doc/vital/Data/Optional.txt
test/Data/Optional.vimspec

Hi :smile:  
I want to add .first(), .last(), .flat_map(), and .optional() to Data.Optional.
How would you think about this? :thinking:

Add more combinators to Data.Optional

---

autoload/vital/__vital__/Data/BigNum.vim
test/Data/BigNum.vim

https://github.com/vim-jp/vital.vim/issues/371 を修正するPRです。
間違っているコードをご指摘下さった @mattn さん, @ichizok さんに感謝いたします。

Data.BigNum: Fix div method

---

autoload/vital/__vital__/Web/HTTP.vim

https://github.com/vim-jp/vital.vim/issues/635

Web.HTTP support HTTP/2

---

README.md
autoload/vital/__vital__/Data/Base32.vim
doc/vital.txt
doc/vital/Data/Base32.txt
test/Data/Base32.vimspec

https://github.com/tsuyoshicho/vital-BaseX
Data.Base64を参考にBase32を作成しました。
Contribute としては今後docを含めたPRを作りたいとは思いますが、直接取り込みでも大丈夫ですので、一旦Issue上で連絡しました。
また、この過程でBase64でも微妙な点があったので、そちらは別立てで連絡します。

Contribute Data.Base32

---

.travis.yml

Ref: https://github.com/thinca/vim-ambicmd/pull/9#issuecomment-496138177

CI: Add homebrew cache on osx

---

README.md
autoload/vital/__vital__/Hash/HMAC.vim
doc/vital.txt
doc/vital/Hash/HMAC.txt
test/Hash/HMAC.vimspec

This module depend Hash.*
Generate HMAC-MD5,HMAC-SHA1 (need SHA1)
---
HMAC (Hash-based Message Authentication Code)  生成モジュールです。
Hash.* を引数に取るので、それらに依存して値を生成します。
SHA1用のテストも準備はしてあるので、SHA1が有効になったら、テストをactivateできます。

Contribute Hash.HMAC

---

test/Hash/HMAC.vimspec

HMAC has any Hash function.
This PR is enable SHA1 HMAC test.

Hash.HMAC: SHA1 test enable

---

Changes

Issue #669 PR
Add no affect description statement.

Changes: add changelog for #647/Hash.MD5 changed work.

---

autoload/vital/__vital__/Random.vim

* Now `docker run --rm -ti -v `pwd`:/src:ro -w /src fnichol/vint --color .` return nothing. Big success!

Random: comment for vint

---

scripts/run-lint-on-ci.sh

* https://github.com/reviewdog/reviewdog/releases
* https://pypi.org/project/vim-vint/

Update reviewdog/vint versions

---

.travis.yml

Set job and jobname setting.
see vim-jp/vim-vimlparser#124

Travis setting update: like vim-jp/vim-vimlparser #124

---

autoload/vital/__vital__/Random.vim

see https://vim-jp.slack.com/archives/C8F0X4DHN/p1562239287236300
This implementation is technical trial.
Please review it.

Random.shuffle(): mattn suggestion implementation

---

autoload/vital/__vital__/Hash/MD5.vim
autoload/vital/__vital__/Hash/SHA1.vim
test/Hash/MD5.vim
test/Hash/SHA1.vim

Update Hash.MD5,Hash.SHA1.
Using previous PRed Data.List.Byte. 
And small add more.
module has Name(using crypto suite eg.HMAC-MD5, HMAC-SHA1) and length

Proposal: update and simply refine Hash(MD5,SHA1) module; using Data.List.Byte functions

---

.appveyor.yml
.travis.yml

Remove notification for Lingr

---

Changes
README.md
autoload/vital/__vital__/Data/Base16.vim
autoload/vital/__vital__/Data/Base32.vim
autoload/vital/__vital__/Data/Base32/Base32.vim
autoload/vital/__vital__/Data/Base32/Crockford.vim
autoload/vital/__vital__/Data/Base32/Hex.vim
autoload/vital/__vital__/Data/Base32/RFC4648.vim
autoload/vital/__vital__/Data/Base64.vim
autoload/vital/__vital__/Data/Base64/Base64.vim
autoload/vital/__vital__/Data/Base64/RFC4648.vim
autoload/vital/__vital__/Data/Base64/URLSafe.vim
doc/vital.txt
doc/vital/Data/Base16.txt
doc/vital/Data/Base32/Base32.txt
doc/vital/Data/Base32/Crockford.txt
doc/vital/Data/Base32/Hex.txt
doc/vital/Data/Base32/RFC4648.txt
doc/vital/Data/Base64/Base64.txt
doc/vital/Data/Base64/RFC4648.txt
doc/vital/Data/Base64/URLSafe.txt
test/Data/Base16.vimspec
test/Data/Base32/Crockford.vimspec
test/Data/Base32/Hex.vimspec
test/Data/Base32/RFC4648.vimspec
test/Data/Base64/RFC4648.vimspec
test/Data/Base64/URLSafe.vimspec

This PR is improve below:
- Data.Base16 imported vital-codec lib. (based routine is Data.List.Byte)
- Data.Base32 and variant imported  vital-codec lib. (refactoring:aggregate internal routine)
- side effect : Base32 RFC test code improved
- Data.Base64 and variant imported vital-codec lib. (refactoring:aggregate internal routine)
- side effect : Base64 RFC test code improved
NOTE:if need PR split. I create per commit PRs.

Data.BaseXX improvement.

---

.appveyor.yml
.travis.yml
Changes
README.md
autoload/vital/__vital__/Bitwise.vim
autoload/vital/__vital__/Data/Either.vim
autoload/vital/__vital__/Data/Optional.vim
autoload/vital/__vital__/Data/String.vim
autoload/vital/__vital__/Random.vim
autoload/vital/vital.vim
doc/vital.txt

すぐに適用することはないかもしれませんが、サポートポリシー的にいつかは必
要になるので、PRを作成
コード上の必要な変更も載せていくつもり

Update support for Vim 8.2/8.1, deprecated Vim 8.0

---

.travis.yml

* It's the blocker for all our pull requests
* e.g. https://travis-ci.org/vim-jp/vital.vim/jobs/638767254?utm_medium=notification&utm_source=github_status

Disable MacVim temporarily

---

autoload/vital/__vital__/Data/String.vim

I'm going to rebase after https://github.com/vim-jp/vital.vim/pull/707

Refactor Data.String.nsplit[EOM]

---

Changes

https://github.com/vim-jp/vital.vim/issues/704

Changes: Mention Data.String fix

---

autoload/vital/__vital__/Text/TOML.vim
doc/vital/Text/TOML.txt
test/Text/TOML.vim

This is the first step for v0.5.0.
Spec:
https://github.com/toml-lang/toml/blob/master/versions/en/toml-v0.4.0.md
https://github.com/toml-lang/toml/blob/master/versions/en/toml-v0.5.0.md
Changelog (what's changed):
https://github.com/toml-lang/toml/blob/master/CHANGELOG.md#050--2018-07-11

Text.TOML: comply with v0.4.0

---

autoload/vital/__vital__/Text/TOML.vim
doc/vital/Text/TOML.txt
test/Text/TOML.vim
test/_testdata/Text/TOML/sample.toml

This is based on #726.
https://github.com/hattya/vital.vim/compare/toml-0.4...toml-0.5

Text.TOML: comply with v0.5.0

---

.travis.yml
scripts/install-lua.sh
scripts/install-vim.sh

Homebrewが明らかなボトルネックなので、MacVimとLuaは自前でダウンロード(&ビルド)した方がよいですね。

CI: Improve test efficiency on travis-osx

---

Changes

Cont'd https://github.com/vim-jp/vital.vim/pull/727

Changelog for Text.TOML

---

test/_testdata/vital/datatest/autoload/vital/__latest__/DataTest.vim
test/vital.vimspec

先日のマージでのvitalizerのテストについて改善可能かの確認のPRです。
可能なら導入できたらいいなとは思います。

Vitalizer: test treat

---

README.md
doc/vital.txt

README and vital.txt add for Color.

doc: README,Color:Update document

---

README.md
doc/vital.txt

resolve #750.
Rewrite README example Vim script code that to be working.
If more better example exists, Please point out changes or direct commit.

Suggestion: example refine to be working

---

autoload/vital/__vital__/Data/BigNum.vim
test/Data/BigNum.vim

Currently Data.BigNum.from_num() call from_string with stringnized args.
This PR is replace to legal generation from num code.

feat: Data.BigNum: from_num method implement

---

README.md

See: https://github.com/vim-jp/issues/issues/1359

Migrate travis-ci.org to .com

---

.appveyor.yml
.travis.yml

themis.vim update v1.5.5
https://github.com/thinca/vim-themis/releases/tag/v1.5.5

ci: themis.vim update to v1.5.5

---

autoload/vital/__vital__/Data/List/Byte.vim

Data.List.Byte from_blob method use blob2list if exists.
and
Data.List.Byte to_blob method use list2blob if exists.
---
レビュアーは、たぶん適切だろうと考えた方をとりあえず設定しています、他の方が適切ならば追加なりをおねがいしたく。

feat: Data.List.Byte: blob2list/list2blob use if exists

---

test/.themisrc

Some tests depends on locale of messages.

Fix the language in test

---

.github/actions/vital-throw-message/Dockerfile
.github/workflows/buildtest.yml
.github/workflows/depup.yml
.github/workflows/reviewdog.yml
.github/workflows/vimhelptagcheck.yml

ci: update checkout v3 & action use golang 1.17

---

.github/workflows/depup.yml

CIでのactionの更新を行います。
移行措置が必要なものはありませんでした。
https://github.com/peter-evans/create-pull-request/blob/main/docs/updating.md

ci: maintenance update
