autoload/vital/__latest__.vim

If you use Ubuntu VM(case sensitive file system) on Mac OS(case
in-sensitive file system) and the &runtimepath is in a shared folder,
the case handling for paths could different with different paths.
It could cause exception, `vital: module not found:`.
ref: https://github.com/Lokaltog/vim-easymotion/issues/171
Do not use tolower() (do not call s:_unify_path()) to get scripts'
self file path.
http://lingr.com/room/vim/archives/2015/02/22#message-21320401

Fix file path case problem

---

README.md
autoload/vital/__latest__/Vim/ScriptLocal.vim
doc/vital-vim-script_local.txt
doc/vital.txt
test/.themisrc
test/Vim/ScriptLocal.vimspec
test/_testdata/Vim/ScriptLocal/absolute.vim
test/_testdata/Vim/ScriptLocal/relative.vim
test/_testdata/Vim/ScriptLocal/symlink.vim
test/_testdata/Vim/ScriptLocal/test.vim

path から `<SID>` を取得したり, script-local な関数を取得したオブジェクト(`sfuncs`) を取得できるモジュールです.
外部モジュールとして実装していた vital-snoop (https://github.com/haya14busa/vital-snoop.vim) が vital 本家にもあると便利という想いによりテストやドキュメントを vital に合わせて移植しました.
実装した関数は4つで
1. `sid({path})`: {path}から`<SID>`を返す　
2. `sfuncs({path})`: {path}からそのpathのscript-local関数を持つオブジェクトを返す
3. `sid2sfucs(<SID>)`: `<SID>`からscript-local関数を持つオブジェクトを返す
4. `scriptnames()`: `<SID>`をキー, pathを値とした辞書を返す. (あとで知りましたが `:h scriptnames-dictionary`と同内容です)
{path}については絶対パスと, `&runtimepath`から見ての相対パスを渡すことができます.
要するに以下のようなことができます.
```vim
let s:V = vital#of('vital')
let s:S = s:V.import('Vim.ScriptLocal')
"" Get <SID> with relative path to &runtimepath
" e.g. starts with autoload/, plugin/, etc...
" (autoload/**/*.vim, plugin/**/*.vim)
:echo …
```

Vim.ScriptLocal: Add ScriptLocal (get script-local things)

---

autoload/vital/__latest__/Vim/ScriptLocal.vim
test/Vim/ScriptLocal.vimspec
test/_testdata/Vim/ScriptLocal/escape%.vim

#258 で `fnameescape()` をしっかりしきれてないことにﾏｯｼﾞされてから気づきました....ｽｲﾏｾﾝ :sweat_drops:

Vim.ScriptLocal: handle special characters in paths

---

autoload/vital/__latest__/Web/HTTP.vim
doc/vital-web-http.txt

This will decode websites served with gzip. 
I came accross a website that didn't respond to accept-encoding, and all the content comes back compressed.
wget has no built in decompression, so the only option would be to pipe it into gunzip or similar. probably a bit of an edge case anyway.
here is a url for testing: http://www.nic-west.com/messages/test.txt

Web.HTTP: add gzip decode to python curl requests

---

autoload/vital/__latest__/Data/Set.vim
doc/vital-data-set.txt
test/Data/Set.vim

python の 2.7 のset ライブラリと 3.4 の仕様(と少しソースコード)を参考に vitalに移植してみました
- ref: https://docs.python.org/3.4/library/stdtypes.html#set-types-set-frozenset

Add Data.Set module

---

autoload/vital/__latest__/OptionParser.vim
doc/vital-option_parser.txt
test/OptionParser.vimspec

OptionParserに以下の2つのextra optionを追加しました。
- 'required': オプションの指定を必須にします。指定されていなければ例外を投げます。
- 'pattern': 'pattern'で指定したパターンにマッチするかどうかチェックします。マッチしなければ例外を投げます。
docとかちょっとアレですがご査収ください。

OptionParser: Add two extra options

---

autoload/vital/__latest__/ConcurrentProcess.vim
doc/vital-concurrent_process.txt
test/ConcurrentProcess.vimspec

ConcurrentProcessは、ProcessManagerやその後継として試作されていたPM2を置き換える別のAPIと機能を持った類似のライブラリです。
Vitalにすでに存在するProcessManager / PM2では、
* アプリケーション側にプロセスの内部状態を確認・調整する責任があり、アプリケーション開発が困難であった
* PMがプロセスに行った行為をトラックするのが難しいため、デバッグにかなり強い推理力と想像力が求められた
* 名前が意味するところが曖昧
などの問題がありました。ConcurrentProcessはこれらの問題を解決しています。
* neoclojure.vimはすでにPM2からConcurrentProcessを用いた実装に置き換えられています。
* https://github.com/ujihisa/neoclojure.vim
* thinca/vim-quickrunにも`runner/concurrent_process`を実装しました。`runner/process_manager`に比べ、かなり短い実装となりました。
* https://github.com/thinca/vim-quickrun/compare/master...ujihisa:concproc?expand=1
* 特に二番目のコミットを見るとconcprocの実際の使用例がわかりやすいのではないかと思います。
現在のConcurrentProcessは、以下をサポートしていませんが、今後(もしかしたら別モジュールに分離した形で)提供したいなと考えているもの:
* autocmd CursorHold/CursorHoldIを用いたイベント登録の簡略化
* Data.Closureとの連携
* …

Add ConcurrentProcess module

---

test/Text/Sexp.vimspec

luaeval() was implemented after +lua.

Text.Sexp: Fix test

---

.travis.yml

.travis.yml: add notifications to lingr

---

autoload/vital/__latest__/Math.vim
doc/vital-math.txt
test/Math.vim

Mathにround()を追加しました。
vimに標準で用意されているroundに桁数を指定する引数(digits)をつけて拡張したものです。
issue #296

Math: add round()

---

Changes
autoload/vital/__latest__/Prelude.vim
doc/vital-prelude.txt

Prelude の deprecated な関数を処理しました．
- `truncate_smart()` と `set_dictionaryhelper()` はずいぶん長い間 deprecated のまま放置されていたので削除しました
- #295 で `Data.String` に移った関数を `Prelude` では廃止扱いにしました．3ヶ月後ぐらい（適当）で削除予定です．（僕が忘れていたら誰か代わりにお願いします）
Changes も書いたので `:Vitalize` 時にメッセージが出るはずです．

Deprecated functions in Prelude

---

autoload/vital/__latest__/Vim/BufferManager.vim

https://github.com/vim-jp/vital.vim/commit/0d24d78da6f8bde448ba7b38f96b9a679b6142d7
上記変更により BufferManager を使うと死ぬので修正

Hotfix: Vim.BufferManager: Remove critical problem

---

autoload/vital/__latest__.vim

@osyo-manga 氏が vital.vim のロードを改善してくれたので、代理で Pull Request します。
コードの変更としては、モジュールのインポート部分をメモ化することでパフォーマンスを改善しています。
私はコメントアウトを削除し一部整形しただけです。
vital のロード部分を設計した @thinca さんにコードをチェックしてもらいたいと思っています。
試しに unite.vim の vital をこれで置き換えてみましたが、特に問題はありませんでした。

Memorize (original code is from manga_osyo)

---

autoload/vital/__latest__/Web/HTTP.vim
doc/vital-web-http.txt

問題
------
Web.HTTPのcurlバックエンドの認証方式がanyauthに決めうちなので、
他の認証方式を明示的に指定するためのオプションが欲しい。
変更点
-------
- Web.HTTP.requestに`authMethod`オプションを追加
- curlでのみ有効（python,wgetでは無視）
- vital-web-http.txtにドキュメントを追加

Specify authorization method in Web.HTTP.curl

---

autoload/vital/__latest__/Data/List.vim

Pythonのenumerateが欲しかったので実装していたんですが，すでにenumerateに相当する`.with_index()`が実装されていたようです．
しかしその実装がLingrでthincaさんに教えてもらったコードよりパフォーマンスが悪かったのでせっかくなのでPRしてみました．
(あとPython勢としては `enumerate()` のaliasが欲しいとも思ったけど，ライブラリ管理するという意味では無駄っぽいので難しそう．ドキュメントに書けば検索で引っかかるのでそれがよいかもしれないけどやってない)
Lingrログ: http://lingr.com/room/vim/archives/2015/06/29#message-22095170
Vim 7.1 か 7.2 のどこかで リストの `map()` で `v:key` が使えるようになったようなのでVimのバージョンにたいする互換性が壊れてる．
そういう意味では無視して頂いてもよいかもしれないです．
`with_index2()`がPRで変更した新しいほうです．
```vim
" similar to python's zip()
function! s:zip(...) abort
return map(range(min(map(copy(a:000), 'len(v:val)'))), "map(copy(a:000), 'v:val['.v:val.']')")
endfunction
" Inspired by Ruby's with_index method.
function! s:with_index(list, ...) abort
let base = a:0 > 0 ? a:1 : 0
return s:zip(a:list, range(base, …
```

Data.List: Improve performance of .with_index()

---

autoload/vital/__latest__/System/File.vim

With `System.File.open()`, I faced the following exception in Windows
```
E194: No alternate file name to substitute for '#': !start rundll32 url.dll,FileProtocolHandler https://github.com/lambdalisue/vim-gita/blob/hotfix/noshellslash_in_windows/autoload/gita.vim#L2
```
It seems that '#' and '%' required to be escaped due to the [`cmdline-special`](http://vimdoc.sourceforge.net/htmldoc/cmdline.html#cmdline-special), so I escape the two character before passing to command line.

System.File: Escape # and % in Windows

---

autoload/vital/__latest__.vim
autoload/vital/__latest__/Bitwise.vim
autoload/vital/__latest__/System/Cache.vim
autoload/vital/__latest__/System/Cache/Base.vim
autoload/vital/__latest__/System/Cache/Dummy.vim
autoload/vital/__latest__/System/Cache/File.vim
autoload/vital/__latest__/System/Cache/Memory.vim
autoload/vital/__latest__/Web/JSON.vim
doc/vital-system-cache-base.txt

実は、モジュールにおいて相互に依存すると、ロード時に無限再帰が発生していました。
発生した無限再帰は #194 が原因で握りつぶされていたのですが、問題なので修正しました。これによっていくつか仕様変更があります。
そもそもの無限再帰の原因ですが、`_build_module()`  → `_vital_loaded()` で別モジュールをロードする時点で、`s:loaded` に生成したモジュールが乗っておらず、めぐりめぐって再び `_build_module()` に戻ってきた時にロード済みのモジュールが使えないのが問題でした。
なぜ乗っていないかというと、一部モジュールで `_vital_loaded()` 時にモジュールを操作していて、これが完了しないと中途半端な状態のモジュールが `s:loaded` に乗ってしまうことになり、このタイミングでロードされると不完全なモジュールがロードされてしまうからです。
`_vital_loaded()` はその名の通りロード済みの時点で呼ばれるべきで、ロードされたあとにモジュールに変更を加えると問題が起きる可能性があるため、`module` にはアクセスできなくしました。
先に挙げたとおり、`Bitwise` などの一部のモジュールは、`_vital_loaded()` でモジュールに対して変更を加えていました。
これは少なくとも現状の利用範囲では、関数を1つずつ定義するなどすれば回避可能でしたが、若干非効率です。
`_vital_loaded()` でモジュールに変更をできなくしたので、代わりに `_vital_export()` を追加し、こちらで変更できるようにしました。
`_vital_export()` では `_vital_loaded()` と違い vital …

モジュールの相互依存を許可する

---

autoload/vital/__latest__/Web/XML.vim

`parse()` が遅かったので、改善しました。
試しに [GitHubのとあるページ](https://github.com/vim-jp/vital.vim/blob/afa4b8d2248fd0e422ffacb4625b3bf565cf75de/autoload/vital/__latest__/Web/XML.vim) の HTML をパースしてみたところ、手元の環境で55秒かかっていたのが2.4秒ほどに短縮されました。

Web.XML: パフォーマンス改善

---

autoload/vital/__latest__/Web/URI.vim
doc/vital-web-uri.txt
test/Web/URI.vimspec

Web.URI に[パーセントエンコーディング](https://en.wikipedia.org/wiki/Percent-encoding)を行う関数を追加しました。
Web.HTTP にある `encodeURI()` と `decodeURI()` に近いものです。(ただしあちらは `application/x-www-form-urlencoded` なので若干違う)
Web.HTTP 側のは、最終的には消すなり別の機能に特化するなりして住み分けたいなと思ってます(しかし詳細はあまり考えてない)。
関連: #108 (無変換は空文字列としました)

Web.URI: Add encode() and decode()

---

autoload/vital/__latest__/Vim/Compat.vim
test/Vim/Compat.vimspec

途中で投げ出した https://github.com/vim-jp/vital.vim/pull/305 の一部。あったほうが何かと便利なので

Vim.Compat: Add a compatible 'writefile' function which support 'a' frag

---

autoload/vital/__latest__/DateTime.vim
doc/vital-date_time.txt
doc/vital-process_manager.txt
test/DateTime.vimspec

'%c' などハンドルできないものが多かったので別メソッドとして追加しました。
ちなみにベンチマークは https://gist.github.com/lambdalisue/e73bd722ca8840e82bd8
追記
`stftime` にマージしました。

DateTime: Fix 'strftime()' to follow timezone of the DateTime object

---

Changes
autoload/vitalizer.vim

hash の衝突の可能性を下げるために full hash を使うようにしました。
ついでに、Changes のいくつかの hash がリポジトリ内に存在しない謎の hash だったので、修正しました。
ref: #6

Don't truncate hash in vitalizer

---

autoload/vital/__latest__/System/Cache/Base.vim
autoload/vital/__latest__/System/Cache/File.vim
autoload/vital/__latest__/System/Cache/Memory.vim
doc/vital-system-cache-base.txt
doc/vital-system-cache-dummy.txt
doc/vital-system-cache-file.txt
doc/vital-system-cache-memory.txt

`System.Cache.File` に `System.Cache.Memory` の内容 (`_cached`) を保持するなどの融合型を作りたかったのですが、`System.Cache.Memory.set()` などが呼び出された場合に自動的に `System.Cache.File.set()` も呼び出したかったので Hook を追加しました

System.Cache: Add a hook method 'on_changed'

---

autoload/vital/__latest__/System/Cache.vim
autoload/vital/__latest__/System/Cache/File.vim
autoload/vital/__latest__/System/Cache/SingleFile.vim
doc/vital-system-cache-base.txt
doc/vital-system-cache-dummy.txt
doc/vital-system-cache-file.txt
doc/vital-system-cache-memory.txt
doc/vital-system-cache-singlefile.txt
doc/vital-system-cache.txt
test/System/Cache/Base.vimspec
test/System/Cache/Dummy.vimspec
test/System/Cache/File.vimspec
test/System/Cache/Memory.vimspec
test/System/Cache/SingleFile.vimspec

While `System.Cache.File` create individual files for individual keys, I made a new cache module which use a single file to store a dictionary of `System.Cache.Memory`.
Users can use this new cache module as a permanent memory cache module.

Add a single file based cache module

---

test/Data/List.vimspec

いい感じにパースしてや...りたかったんですがちょっと面倒そうだったので
sideways.vimとマクロを使って目視で変更しました．
`/\vAssert Equals\([^Lla]` した限りでは修正抜けは無いことになっています．

Data.List: Fix order of args for Assert Equals()

---

autoload/vital/__latest__/Web/JSON.vim
doc/vital-web-json.txt
test/Web/JSON.vimspec

With this changes, `s:JSON.encode({obj}, { 'indent': 2 })` encode `{obj}` into a JSON string **with indents**.
```vim
echo s:JSON.encode({'a': 0, 'b': 1})
" => '{"a":0,"b":1}'
echo s:JSON.encode({'a': 0, 'b': 1}, {'indent': 2})
" => '{
"   "a": 0,
"   "b": 1
" }'
```

Web.JSON: Encode JSON with indents

---

README.md
autoload/vital/__latest__/Data/Counter.vim
doc/vital-data-counter.txt
doc/vital.txt
test/Data/Counter.vimspec

Data.Counter is similar to python's collections.Counter
- https://docs.python.org/3.5/library/collections.html#collections.Counter
- https://github.com/python/cpython/blob/a49faa270dbdc0ce4cb8b79d98915434e019533a/Lib/collections/__init__.py#L446-L448
I'll add document later but the implementation is done and I assume you can understand most of behavior from comments, tests and python's documentation of collections.Counter.
Please take a look when you have time.

Data.Counter: Implement "Data.Counter"

---

autoload/vital/__latest__/Web/URI.vim
doc/vital-web-uri.txt
test/Web/URI.vimspec

This pull requests allows each URI component configurable.
Each component is represented by PatternSet object.
(Below is the quote from help document)
PatternSet object is the set of patterns for URI syntax.
This object has each method for URI components based on RFC3986
and all components are fully customizable.
e.g.: scheme(), host(), path(), ...
Below is the example how to customize URI component definition.
This example allows more tolerant URI parsing.
(This example is from https://github.com/tyru/open-browser.vim/issues/72)
The default PatternSet is very strict
because it is completely RFC3986 based implementation.
(_default_ means the object which
*Vital.Web.URI.new_default_pattern_set()* returns)
According to RFC3986, URI allows
* ' (single quote)
* ( (left parenthesis)
* ) (right …

Web.URI: Make each URI component configurable

---

autoload/vital/__latest__/Web/HTTP.vim

2点修正が含まれていますがまとめてしまいました。
- curl で header が空で帰ってきた場合に E683 になる問題を修正
- curl/wget コマンドの詳細なエラー情報を復帰
- curl では、header が空ではないが復帰値が 0 ではない場合があったので、 header が空かどうかをチェックするようにしました。

Web.HTTP: Improved error messages

---

README.md
appveyor.yml
autoload/vital/__latest__/Vim/Python.vim
doc/vital-vim-python.txt
doc/vital.txt
test/Vim/Python.vimspec
test/_testdata/Vim/Python/test.py

Vim.Python: Add a new module for +python/+python3 compatibility functions

---

README.md
autoload/vital/__latest__/Vim/Guard.vim
doc/vital-vim-gurad.txt
doc/vital.txt
test/Vim/Guard.vimspec

Example
```vim
let s:G = s:V.import('Vim.Guard')
let guard = s:G.store('&backup', 'g:foo', ['foo', s:])
" do something
call guard.restore()
```

Vim.Gurad: A module to store/restore option/variable values

---

Changes
autoload/vital/__latest__/Web/URI.vim
autoload/vital/__latest__/Web/URI/HTTP.vim
autoload/vital/__latest__/Web/URI/HTTPS.vim
doc/vital-web-uri.txt
test/Web/URI.vimspec

#364 を実装しました。
- `s:URI.clone()`
- `s:URI.relative({reluri})`
以下のコードはhelpより抜粋しました。
```viml
let s:URI = vital#of('vital').import('Web.URI')
let uri = s:URI.new('http://example.com/')
let copyuri = uri.clone().relative('/a/b/c')
echo uri.to_string()
" => 'http://example.com/'
echo copyuri.to_string()
" => 'http://example.com/a/b/c'
```

Pull Request: Web.URI で相対 URI を扱いたい

---

autoload/vital/__latest__/Vim/Buffer.vim

writefile({content}, {filename}, 'b') eliminates a terminal empty line so 'b' should not be used.
https://gist.github.com/lambdalisue/930d46ba2a9a969c4e93#file-test-vim
Before: The script above show "no difference"
After : The script above correctly show the difference
Close #384

Vim.Buffer: Fix read_content()/edit_content() for a terminal empty line

---

autoload/vital/__latest__.vim
autoload/vital/__latest__/Vim/Guard.vim
autoload/vitalizer.vim
doc/vital.txt

vital のローダーの改善です。かなりあちこちいじりましたが、大きな変更点は 3 つあります。
1. #137 の解決
プラグイン内に `autoload/vital/__latest__` を置いておけば、この中身は `:Vitalize` しなくても使えるようになります。(ローダー自体を入れるため、`:Vitalize` 自体は必要になります。)
2. ロードの高速化
昔の vital は、`runtimepath` 中の同じバージョンの vital を共有するために、`runtimepath` 内の全てのファイルを探していました。
今は事情が変わっていて、各プラグインは自分用にファイルを持っていて、それだけを使うようになっています。
もはやロード時に `runtimepath` を捜査するのは無駄であるので、自分自身が持っているファイルのみを探すようにしました。
計測はしていないので申し訳ないんですが、`runtimepath` が大きい人ほど相対的にロード処理が速くなるはずです。
3. vital のモジュール一覧の保存位置の変更
上記2つを解決するために、プラグインが普段使う vital のモジュールファイルの一覧と、vitalizer が使うモジュールファイルの一覧を変える必要がありました。vitalizer は相変わらず `runtimepath` からファイルの一覧を探すからです。
そこで、ちょっとトリッキーな構造になってしまいましたが、`vital#of()` で得られる vital loader のオブジェクト自体にファイルの一覧を置き、`vitalizer` は使用時にこの一覧を置き換える形にしました。
各モジュール関数が `dict` 関数になってしまうので正直微妙な感じもするのですが、とりあえず困ることはないだろうという妥協案です。 …

Improve vital loader (fix #137)

---

autoload/vital/__latest__.vim

ref: #370 https://github.com/vim-jp/vital.vim/pull/370/files#discussion_r51004044
`s:_unify_path()`呼び過ぎによって遅くなったので最小限呼ぶように修正．
計測データはまた貼ります．
一応lingr logに雑にはってある: http://lingr.com/room/vim/archives/2016/01/31#message-23002109

Fix performance for #370

---

autoload/vital/__latest__/System/Filepath.vim
doc/vital-system-filepath.txt
test/System/Filepath.vimspec

http://lingr.com/room/vim/archives/2016/02/02#message-23010490
> ところで話が変わるのだけど、vitalizer の関係で、特定のパスが特定のパスを含んでいるか、みたいな判定をする機能が System.Filepath 辺りに欲しい

System.Filepath: Add contains({path}, {base})

---

doc/vital-date_time.txt

A tag requires the surrounding blank.

DateTime: Fix helptags

---

autoload/vital/__latest__/System/File.vim
doc/vital-system-file.txt

細かい修正をいくつか含んでいますが、メインは組み込み関数 `delete()` の新しい `{flags}` 引数への対応です。
`delete()` の `{flags}` は追加されてから何度かバグの修正が入っていたので、現時点で最後に修正されたバージョンを利用可能バージョンとして指定しました。

System.File: Some improves

---

autoload/vital/__latest__/Vim/Guard.vim
doc/vital-vim-guard.txt
test/Vim/Guard.vimspec

Now you can
```vim
let list = []
let dict = {}
let guard = s:Guard.store('@a', '$PATH', [list], [dict], [list, 1], [dict, 1])
```

Vim.Guard: Support registers, environment variables, values in list or dict

---

autoload/vital/__latest__.vim

When there are two or more plugins that uses vital and they are placed to the
same runtimepath, `plugin_name()` returns wrong name.

Fix plugin_name()

---

autoload/vital/__latest__.vim

I found a small mistake in s:_uniq.
```vim
echo uniq(['foo', 'foo', 'foo', 'bar', 'bar', 'bar'])
function! s:_uniq(list) abort
let i = len(a:list) - 1
while 0 < i
if a:list[i] ==# a:list[i - 1]
call remove(a:list, i)
let i -= 2
else
let i -= 1
endif
endwhile
return a:list
endfunction
echo s:_uniq(['foo', 'foo', 'foo', 'bar', 'bar', 'bar'])
```
```
['foo', 'bar']
['foo', 'foo', 'bar', 'bar']
```
This pull request fixes the behaviour.
```vim
echo uniq(['foo', 'foo', 'foo', 'bar', 'bar', 'bar'])
function! s:_uniq(list) abort
let i = len(a:list) - 1
while 0 < i
if a:list[i] ==# a:list[i - 1]
call remove(a:list, i)
endif
let i -= 1
endwhile
return a:list
endfunction
echo s:_uniq(['foo', 'foo', 'foo', 'bar', 'bar', 'bar'])
```
```
['foo', 'bar']
['foo', 'bar']
```
What do you think?

__latest__: fix s:_uniq

---

autoload/vital/__latest__/Vim/Compat.vim

ふと気が向いたので、誰も使わないであろう `Vim.Compat.has_version()` を `:help has-patch` に対応してみました。

Vim.Compat: has_version(): Use has-patch

---

autoload/vital.vim

ref: #259
一斉に修正が反映されないのと修正しないのは話が別問題で，互換性がある変更なら修正していくべきかと思います．
どうせ #415 とかで deprecated にするけど，それでも `vital#of` の後方互換性のために autoload/vital.vim を配らないようになるというのは，やるとしてもすくなくともまだ先だし，バグのない autoload/vital.vim にしておいて損はないハズ．

vital: add {nosuf} arg for globpath() in vital#of()

---

appveyor.yml

If you do a lot of commits producing queued builds, git checkout operation following git clone can fail because requested commit is not present in a cloned repository.
ref: https://www.appveyor.com/docs/how-to/repository-shallow-clone#setting-depth-of-git-clone-command

Appveyor:  Clone depth number is too small

---

appveyor.yml
test/Vim/Python.vimspec
test/_testdata/Vim/Python/test.py

#408 の引き継ぎです．
ref:  #416, #408
とにかく files.kaoriya.net から vim-jp/redirect に移行するための最小変更です．
oldestはpython default 2.6 が使われるので `version_info` の変更は必要です．
pythonはまた別に指定すればいいでしょう．全体としてpython 2.6をサポートするかとかなると疑問も残りますし (ref #430)
だいぶpending してるし，非互換な変更いれるわけではないので 1 LGTM くらいでマッジされたい

Stop to use files.kaoriya.net

---

autoload/vital/__vital__/Prelude.vim

変数を使う必要がなかったので。ついでに ``v:version`` の比較方法を他と合わせました。

Prelude: refactor glob()

---

autoload/vital/__vital__/Prelude.vim

Patch 7.4.279 で `globpath()` の引数に `{list}` が追加されました。

Prelude: improve globpath()

---

autoload/vital/__vital__/Data/Closure.vim

In latest Vim, `dict.func` returns a Partial.  And they are compared including the internals.  We don't expect it.

Data.Closure: Fix for Partial

---

autoload/vital/__vital__/Vim/Buffer.vim
test/Vim/Buffer.vimspec

`read_content()` を呼ぶと tempfile が unlisted-buffer として残るが、無駄なので消したい。

Vim.Buffer: Cleanup tempfile buffer in read_content()

---

autoload/vital/__vital__/Bitwise.vim
autoload/vital/__vital__/Random/Mt19937ar.vim
autoload/vital/__vital__/Random/Xor128.vim
doc/vital-bitwise.txt
doc/vital-random-mt19937ar.txt
doc/vital-random-xor128.txt
test/Bitwise.vimspec
test/Math.vim

Vim に +num64 feature が追加され、整数のサイズが 64bit になり、その影響でいくつかのモジュールの動作がおかしくなった。
- Bitwise
- Random
- Random.Xor128
- Random.Mt19937ar
この PR はこれらを修正する。

Fix for 64bit number

---

autoload/vital/__vital__/OptionParser.vim

This also locks copied parser.  This is unuseful.

OptionParser: Remove extra lockvar!

---

Changes
autoload/vital/__vital__/Vim/BufferManager.vim

Vim.BufferManager: Drop deprecated functions

---

doc/vital-option_parser.txt

0. Remove invalid option (`{short-name}` is already deleted)
0. Alignment

Fix doc (vital-option_parser.txt)

---

autoload/vital/__vital__/Data/String.vim

#359 を踏まえて幾つか `strwidthpart` の実装突っ込んでベンチマークとってみました（スクリプトは `benchmark/vital-data-string.vim` です）。
ちなみに lua 版は面倒だったのでとりあえず https://github.com/starwing/luautf8 が入っている前提です（だからテスト落ちます）。
```
strwidthpart: 0.397516 s
strwidthpart_lua: 0.158421 s
strwidthpart_type1: 0.303116 s
strwidthpart_type2: 0.071376 s
*** time: 7.049161 ***
```
圧倒的に ynkdir さんタイプ (type2) が早いので TAB 文字の扱いは tyru さんの言うように空白に置き換える形で吸収して、これを使いたいなーと思うのですがどうでしょうか？

Data.String: 遅いのなんとかする

---

autoload/vital/__vital__/Vim/Buffer.vim
doc/vital-vim-buffer.txt
test/Vim/Buffer.vimspec

- `read_content()` で挿入位置を指定可能にした
- `read_content()` や `edit_content()` で使う `{options}` を作るメソッドを追加
- <del> `open()` で使う（文字列の） `opener` が preview-window を開くか判断するメソッドを追加 </del>
<del> 最後のプレビューか判断する奴の使用用途は「バッファが開いてからコンテンツを書き換えたいが preview-window だとフォーカスが動かないので preview-window の場合は明示的に `wincmd P` を呼び出したい」などの場合用です。 </del>

Improve vim buffer

---

autoload/vital/__vital__/Data/String.vim
doc/vital-data-string.txt
test/Data/String.vimspec

Data.String.remove_ansi_sequences() は渡した文字列中の制御コードを削除するものですが、試した感じではうまく動作していないようでした。
手元環境の制御コードでしか動作確認していないので、WindowsやMacなどでも動かしていただいたほうが良いかもです。
```vim
" Before output: "\033[47m\033[32mGreen\033[0m"
" After output: "Green"
echo s:S.remove_ansi_sequences("\033[47m\033[32mGreen\033[0m")
```

Data.String.remove_ansi_sequences() is broken ?

---

autoload/vital/__vital__/Web/URI.vim

Web.URI: Use robust operators !=# instead of !=

---

doc/vital/Math.txt

The result of `nr2str(10, 2)` is `"1010"`.
It seems to be confused with `str2nr("10", 2) == 2`.

Fix Vital.Math.nr2str() example

---

autoload/vital/__vital__/Process.vim
doc/vital/Process.txt

NeoVimの`:h system()`によると
「system()で'&'を付けて実行はできないので、代わりにjobstart()を使って下さい」
とのことですが、ここでjobstart()ぶちこむのは違う気がするのと、すごいめんどくさそうなのでこれでどうでしょうか！

Avoid executing system() with '&' on neovim

---

autoload/vital/__vital__/ConcurrentProcess.vim
autoload/vital/__vital__/Database/SQLite.vim
autoload/vital/__vital__/Experimental/Functor.vim
autoload/vital/__vital__/Interpreter/Brainf__k.vim
autoload/vital/__vital__/Random/Xor128.vim
autoload/vital/__vital__/Text/Lexer.vim
autoload/vital/__vital__/Text/Parser.vim
autoload/vital/__vital__/Web/URI.vim
autoload/vital/__vital__/Web/XML.vim

エラーメッセージのフォーマット（ `vital: {module name}: ...` ）が統一されていない箇所を直しました．

Unify error message format (vital: {module name}: ...)

---

autoload/vital/__vital__/Process.vim

ref. #467 
@rhysd さんが Twitter で呟いてて、確かにそうだと思ったので修正しました。
> ん，これは neovim でバックグラウンド実行したら jobstart() かエラーにすべきじゃないのか…
> https://twitter.com/Linda_pp/status/820171056186986496
#467 で入ったドキュメントの文言の修正は必要ないと思ったのでやっていません。

Process: system() should throw if "&" was given on neovim

---

autoload/vital/__vital__/Vim/Buffer.vim
doc/vital/Vim/Buffer.txt

1. Fix 'no such buffer' exception during 'read_content' (ref: https://github.com/lambdalisue/vim-gista/issues/81#issuecomment-271821407)
2. Add 'lockmarks' option to lock marks on the buffer

Fix and improve Vim.Buffer.read_content/edit_content

---

scripts/install-vim.sh

`return` must not be appeared outside of a function or a sourced script.

CI: Fix install-vim.sh

---

README.md

@rhysd さんからもらったアドバイスの件を追記しました。 https://github.com/vim-jp/vital.vim/issues/367#issuecomment-273769152
> README に [wiki](https://github.com/vim-jp/vital.vim/wiki/External-vital-modules) へのリンクがあると良い気がします．

Add a link to "External vital modules" to README

---

autoload/vital/__vital__/Bitwise.vim
test/Bitwise.vimspec

Vim 8.0.0219 change the behavior of overflow and now any literal
larger than or equal to 0x8000000000000000 will be rounded to
0x7FFFFFFFFFFFFFFF.
To fix this problem, create values without using literal in code and tests.
https://github.com/vim-jp/vital.vim/issues/479
こんなんでどうでしょう？

Bitwise: Fix overflow from Vim 8.0.0219

---

doc/vital.txt

I noticed that `:h vital.vim` doesn't show introduction of vital.vim. [Link to `vital.vim`](https://github.com/vim-jp/vital.vim/blob/06f830e2c10ee26f94b5665c73da72c6c9b422c5/doc/vital.txt#L40) even exists... So I added it.
(Note that `:h vital` also can't lead users to introduction page because tag is case sensitive. Should we change `Vital` tag to `vital`?)

Fix tags in introduction document

---

Changes
autoload/vital/__vital__/Vim/Buffer.vim
autoload/vital/__vital__/Vim/BufferManager.vim
doc/vital/Vim/Buffer.txt
doc/vital/Vim/BufferManager.txt
test/Vim/Buffer.vimspec
test/Vim/BufferManager.vimspec

Improve Vim.Buffer / Vim.BufferManager

---

autoload/vital/__vital__/DateTime.vim

Tests failed on Windows 64 because `REG_DWORD` is 32 bit long number,
but integers are stored on 64 bit, thus it have to be expanded to 64 bit
to get the right value (for negative numbers).

DateTime: Fix timezone on Windows 64 bit + Vim 32 bit

---

scripts/install-vim.sh

It seems `brew upgrade` is required to upgrade the version of Python on Mac OS X in Travis

Fix tests on Mac OS X in Travis

---

test/Vim/Message.vimspec

Reverts vim-jp/vital.vim#491  
8.0.0547 で治るらしいので

Revert "Vim.Message: fix test after Vim 8.0.0467"

---

autoload/vital/__vital__/Data/List.vim
doc/vital/Data/List.txt
test/Data/List.vimspec

I want to use lambda expression in .find() .
- - -
But this supports only if vim has +lambda .
Can I add this ?

Data.List: Add funcref support for .find()

---

doc/vital/Data/Optional.txt

Data.Optional: s/end/endfunction/

---

doc/vital/Data/Either.txt

`return` may not be the identity of the monad in unclearly context :bow:  
特に「returnはモナドの単位元やで」って直接言ってしまった @rhysd さんに対して、誤った知識をすみません :bow:

Data.Either: Fix the document of .return()

---

autoload/vital/__vital__/Text/Lexer.vim

* Text.Lexer.token()
Changed to private method.
* Text.Lexer.simple_parser()
Deprecated.

updated lexer doc. 

---

autoload/vital/__vital__/Data/OrderedSet.vim

Data.OrderedSet.version() を消しました。
Changes に書くべきか悩みましたが、 #522 と同じく undocumented なメソッドの仕様変更ということで書きませんでした。
ref. #440

Data.OrderedSet: Remove version()

---

doc/vital/Data/String.txt
doc/vital/Mapping.txt
doc/vital/Web/URI.txt
doc/vital/Web/URI/HTTP.txt
doc/vital/Web/URI/HTTPS.txt

Add the following doc.
ref. #440
- Mapping.execute_abbr_command()
- Mapping.execute_map_command()
- Mapping.execute_unmap_command()
- Mapping.get_abbr_command()
- Mapping.get_all_modes()
- Mapping.get_all_modes_list()
- Mapping.get_map_command()
- Mapping.get_unabbr_command()
- Mapping.get_unmap_command()
- Mapping.is_mode_char()
- Mapping.options_chars2dict()
- Mapping.options_chars2raw()
- Mapping.options_dict2chars()
- Mapping.options_dict2raw()
- Web.URI.clone_pattern_set()
- Web.URI.HTTP.canonicalize()
- Web.URI.HTTP.default_port()
- Web.URI.HTTPS.canonicalize()
- Web.URI.HTTPS.default_port()
- Data.String.strchars()

Add missing doc

---

autoload/vital/__vital__/Web/URI.vim
test/Web/URI.vimspec

via https://github.com/tyru/open-browser.vim/issues/96

Web.URI: fix: URI.new_from_seq_string('foo bar: baz') was wrongly accepted

---

autoload/vital/__vital__/Process.vim
test/Process.vimspec

Windows における `shellescape()` が結果をダブルクォートで囲んでいなかったので，囲むようにしました．
ただ，ここが自力でエスケープしようとしているのは，多分標準の `shellescape()` が Windows の cmd.exe はダブルクォートで囲まないといけないのに `shellslash` が on のときはシングルクォートで囲んでしまうからですよね？それであれば，自力でエスケープしなくても上の `s:spawn` でやっているように一時的に `shellslash` をオフにしてしまえば良いのかなと思うのですが，それだとまずいでしょうか？

Process: Fix shellescape() on Windows

---

.travis.yml

Recently, Travis-CI switched to Ubuntu trusty. At the same time, rvm was introduced and it caused a link error when building vim with if_ruby.
Disable rvm and use the system ruby to fix the problem.
Actually, if_ruby might not be needed...
Related: #540

Fix ruby build

---

doc/vital/OptionParser.txt

Vim seems to generate helptags of `*NOT*` keyword in doc/OptionParser.txt .

OptionParser: doc: Remove *NOT* tag

---

test/Process.vimspec

Ref. #535
`echo 1234` in cmd.exe outputs `1234<space><CR><NL>`.
Vim's system() truncates `<CR>`.
so expected output is `1234<space><NL>`

Process: Fix test on Windows

---

scripts/install-vim.sh

I improved the time to spend for running CI.
Before: 10 minutes https://travis-ci.org/vim-jp/vital.vim/builds/285078709
After: 6 minutes https://travis-ci.org/rhysd/vital.vim/builds/285091846
Bottleneck was preparing environment for tests on macOS on Travis CI.
Changes are following:
- Use MacVim instead of Vim because many users use MacVim, not a pure Vim on macOS
- MacVim can be built with system Python. So installing/upgrading `python` package is no longer needed
- `brew update` is automatically done in `brew install` so we don't need to do it manually.
- `brew upgrade` updates all outdated packages but they are not needed in our tests

Make CI 1.7x faster

---

.travis.yml
scripts/install-vim.sh

CI fails after #542 was merged.
https://travis-ci.org/vim-jp/vital.vim/jobs/285464273#L1726
(Not sure why no error occurred in the PR #542 itself.)
Execute "rvm reset" only on Linux.
Execute "brew update" before "brew install".

Fix mac build

---

.travis.yml
scripts/install-vim.sh

Related: #543 
* [brew 1.3.5](https://github.com/Homebrew/brew/releases/tag/1.3.5) から ruby 2.3 以上が必要になった
`brew-update` で ruby (2.3) をダウンロードしてそれを使うようになっているのですが、`brew-install` 内で `brew-update` を実行されると `brew-install` 側では更新前の ruby (2.0) を指しているためにバージョンチェックでエラーになってしまうという構図でした。
#542 が、PR の CI は通ったのにマージしたら fail したのは、この間に brew のバージョンが上がったためです。
ということで、以下のように変更しました。
* 明示的に `brew-update` を実行
* `HOMEBREW_NO_AUTO_UPDATE=1` を設定し、 `brew-install` 内では `brew-update` しない

Set `HOMEBREW_NO_AUTO_UPDATE`

---

autoload/vital/vital.vim

`:redir` can not nest, but `execute()` can nest.
Use `execute()` if possible.

Avoid redir in vital loader

---

autoload/vitalizer.vim

READMEの通り，（https://github.com/vim-jp/vital.vim/blame/master/README.md#L90)
```vim
:Vitalize --name=your_plugin_name $HOME/.vim/bundle/your_plugin_dir/
```
を実行しようとしてみたところ， `vitalizer: {target-dir} must exist.` という例外が投げられます．
READMEから察するに，環境変数は使えるべきだと判断し，この修正を行いました．
もし，意図して `expand` していないのであれば，READMEを修正するべきかなと思いました．
一応，再現手順を書いておきます．
（ホームディレクトリに foo というディレクトリがない前提）
```vim
:!mkdir ~/foo
:Vitalize --name=test $HOME/foo
" => vitalizer: {target-dir} must exist.
```
`:Vitalize` 及び， `vitalize#command()` の テストが存在しなかったので，もし必要であれば書きます．
(別のPRのほうが良いかもしれない？）

Fix to failure `:Vitalize` when included environment in args.

---

doc/vital/System/Filepath.txt

Close #545 
Original PR (#545) which introduce `path_separate()` function was rejected
because `split(path, path_separator())` was enough.
However, `path_separator()` lacks its example in the document.

System.Filepath: doc: add example to path_separator()

---

doc/vital/System/Filepath.txt

via #548 
As @k-takata was pointing out, `path_separator()` example is not correct (the right place of the example is `separator()`).
* Move `path_separator()` example to `separator()`
* Add `path_separator()` example (which @k-takata gave [here](https://github.com/vim-jp/vital.vim/pull/548#issuecomment-342700768))

System.Filepath: doc: fix path_separator()/separator() examples

---

autoload/vital/__vital__/Data/Dict.vim
doc/vital/Data/Dict.txt
test/Data/Dict.vimspec

`Data.Dict.from_array()` can make a dictionary from an array like `[key, value, key, value, ...]` or `[[key, value], [key, value], ...]`.

Data.Dict: Add .from_list()

---

autoload/vital/__vital__/Data/Base64.vim

`s:urlsafe_table` seems unused. what is this purpose? >@mattn (this module's author)

Data.Base64: Remove unused variable

---

.codecov.yml
.coveragerc
.travis.yml
README.md
appveyor.yml
test/.themisrc

https://github.com/Vimjas/covimerage

Introduce covimerage for test coverage

---

autoload/vital/vital.vim

`execute()` has a bug.  This PR avoid it.
See also(Japanese): https://github.com/vim-jp/issues/issues/1129

vitalizer: Avoid the bug of execute()

---

autoload/vital/__vital__/System/File.vim

Use `glob()` directly.
Here is Prelude's code:
```vim
if v:version > 703 ||
\  (v:version == 703 && has('patch465'))
function! s:glob(expr) abort
return glob(a:expr, 1, 1)
endfunction
else
function! s:glob(expr) abort
return split(glob(a:expr, 1), '\n')
endfunction
endif
```
Vital.vim now supports Vim 7.4 or later so we can use third argument of `glob()`.

System.File: Remove dependence to Prelude module

---

README.md
doc/vital.txt

While reviewing #560, I noticed that supported version by vital.vim is not documented. Let's say vital.vim supports Vim 7.4 or later explicitly in documentation.

Let's say vital.vim supports Vim 7.4 or later in doc

---

README.md
autoload/vital/__vital__/Async/Promise.vim
doc/vital.txt
doc/vital/Async/Promise.txt
test/.themisrc
test/Async/Promise.vimspec

This PR takes over #526 because its timeline is too long.
I rebased the branch into 7 commits. Please see #526 for the detail of design of this library.
As described in #526, this PR only implements APIs of ES6 promises. So discussion for adding other (maybe useful) APIs is out of scope. Let's start from small library. After the smallest set of Promise is added to master branch, we can try it in real Vim plugin. And then, let's discuss further rich APIs (like [bluebird](http://bluebirdjs.com/docs/api-reference.html)).
In this PR, I want to
- brash up implementation/documentation
- fix bugs
- add missing test cases
Thank you for your review in advance.
As of #526, either English or Japanese is ok.

Review: Async.Promise

---

autoload/vital/__vital__/Web/XML.vim
test/Web/XML.vimspec

When parsing `<tag attr=""/>`, currently the value of `attr` is parsed as `'attr'`. But it should be `''` in XML. I fixed the point.
ref: https://twitter.com/mattn_jp/status/952766828199030784

Web.XML: Fix handling empty attribute values

---

autoload/vital/__vital__/Async/Promise.vim
doc/vital/Async/Promise.txt
test/Async/Promise.vimspec

I implemented .finally() method to Promise object.
.finally() is a method which executes its callback when the receiver is settled (whether resolved or rejected). It is similar to :finally.
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/finally
Now `Promise.prototype.finally` is on stage4 (last phase for being the part of ECMAScript spec). So it'll be standard soon.
https://github.com/tc39/proposal-promise-finally#readme

Async.Promise: Add .finally() method to Promise object

---

autoload/vital/__vital__/DateTime.vim

Current implementation on Windows use Windows registory since %z on Windows return '東京 (標準時)'. But it is bit slow. strftime('%c', 0) must be epoch based on 1970/1/1 0:0:0, so hours and minutes
must be time offset.

DateTime: use strftime('%H %M', 0) on Windows

---

autoload/vital/__vital__/System/Filepath.vim
doc/vital/System/Filepath.txt
test/System/Filepath.vimspec

@mattn++ and @lambdalisue++
3年前から眠っていた https://github.com/vim-jp/vital.vim/pull/358 を古の眠りから覚まして改めて作ってみました。
mattnさんのコミットをベースに、document書いてtest追加したものがこちらとなっております。
https://github.com/vim-jp/vital.vim/pull/358 の方針のとおり。名前変えようという話もあったけど、3年そのままだったし、このままでまずマージするのがよさそうな気がしてます。

System.Filepath: Add to_slash() and from_slash()

---

.travis.yml
scripts/coverage.sh
scripts/install-vim.sh
scripts/run-lint-on-ci.sh

I made running CI faster.
Before: https://travis-ci.org/vim-jp/vital.vim/builds/390362502
After: https://travis-ci.org/rhysd/vital.vim/builds/390389523
Total: 5min 47sec -> 4min 2sec (1min 45sec faster)
Optimizations:
- Enabled a binary package (bottle) on macOS worker by removing installation options which prevented it. (4m54s -> 2m58s)
- macOS worker is slow to start. It was a bottleneck.
- Removed Lua dependency since Lua was not actually used in CI. (`--with-lua` could be omitted by this change)
- Link `vim` executable directly (`--with-override-system-vim` could be omitted by this change)
- Separate running linters into another job.
- Since it took 200s.
- After optimizing macOS worker, the job which run linters was a bottleneck.
I assigned people as reviewers who would be familiar …

Make CI faster

---

doc/vital/Data/List.txt

https://github.com/vim-jp/vital.vim/issues/592
(One thing I noticed was that `sort_by` is non-destructive while `sort` is destructive. I'd like to leave that decision here but you can think for future. Most of Data.List functions are non-destructive, so it might sound reasonable to change `sort` also non-destructive, but I believe the best is to provide both destructive/non-destructive sort and sort_by, since sorting often take giant lists which effects GC time.)
Handy links for reviewers
* test https://github.com/vim-jp/vital.vim/blob/master/test/Data/List.vimspec
* implementation https://github.com/vim-jp/vital.vim/blob/master/autoload/vital/__vital__/Data/List.vim

Data.List: Clarify which destructive/non-destructive explicitly

---

autoload/vital/__vital__/Web/HTTP.vim

Currently `Web.HTTP.request()` function does not work with `HEAD` HTTP method when client is curl.
```vim
let V = vital#of('vital')
let HTTP = V.import('Web.HTTP')
echo HTTP.request('http://example.com', {"method": 'HEAD', "client": 'curl'}) " Stop this program here!
```
curl(1) does not support `-X HEAD`.
```bash
$ curl -X HEAD http://example.com
Warning: Setting custom HTTP method to HEAD with -X/--request may not work the 
Warning: way you want. Consider using -I/--head instead.
```
Use `--head` option instead of `-X HEAD`.

Web.HTTP: Support HEAD method for curl client

---

.appveyor.yml

ref. Vimjas/covimerage#57, #608 
Now the new version of covimerage is uploaded to PyPI.
So let's fix the command name again.
@ujihisa @thinca Sorry! please approve this again.

write-coverage -> write_coverage

---

Changes
autoload/vital/__vital__/Data/Optional.vim
doc/vital/Data/Optional.txt
test/Data/Optional.vimspec

現在の `.get_or` は代替として値を受け取っており、こういうときに不便 :sob:
```vim
let s:Msg = vital#foo#import('Vim.Message')
let x = s:なんかOptionalを返すやつ()
call s:Optional.get_or(x, s:Msg.error('無効な値がきたよ'))
" ↑ 本当はxがnoneだった場合にerrorを表示したいけど、
"    これだとどちらにせよerrorが表示されちゃう
```
```vim
let s:Msg = vital#foo#import('Vim.Message')
let x = s:なんかOptionalを返すやつ()
call s:Optional.get_or(x, { -> s:Msg.error('無効な値がきたよ') })
" ↑ xがnoneのときだけerrorが呼ばれる
```
- `.get_or`に破壊的変更が入る
- `.get_or_else`という名前で新しく生やすのもいいと思うんだけど、  
ユーザー的にわかりにくかったりするかどうかというのを考えている。  
（どうでしょうか…… :thinking:）

Data.Optional: Expect functions as the alternative of .get_or

---

autoload/vital/__vital__/Deprecated/Lua/Prelude.vim
autoload/vital/__vital__/Deprecated/Text/Sexp.vim
autoload/vital/__vital__/Interpreter/Brainf__k.vim

`luaeval()` で評価した式がtableを返したり (`dofile()` など) 値を返さなかったり (`print()` など) すると cannot convert value エラーになるので、明示的に戻り値を指定しました。

Fix calling luaeval()

---

Changes
autoload/vital/__vital__/Data/Optional.vim
doc/vital/Data/Optional.txt
test/Data/Optional.vimspec

I want to extract `O.some(O.some(10))` to `O.some(10)` :dog2:
And In my opinion, `.flatten` is a basic name for a monad's function :cold_sweat:
This introduce a breaking changes for that :sunglasses::+1:

Data.Optional: Improve arround .flatten()

---

autoload/vital/__vital__/Data/List.vim
doc/vital/Data/List.txt
test/Data/List.vimspec

Ruby has the following feature:
```ruby
Array.new(10) { rand(10) }
#=> [1, 9, 5, 0, 7, 0, 3, 3, 8, 2]
```
With this patch, you can do similar thing with vital.vim.
```vim
s:List.new(10, { -> s:Random.range(0, 9) })
"=> [1, 9, 5, 0, 7, 0, 3, 3, 8, 2]
```

Data.List: add new()

---

autoload/vital/__vital__/System/File.vim

Also fixing encoding of arguments
Fixes #616 
For fixing this, I removed part throwing exceptionin rmdir and fallback to rm-rf command since there are no sense of unity for code. I may add this again.
```vim
if v:shell_error	
let ret = iconv(ret, 'char', &encoding)	
throw 'vital: System.File: rmdir(): ' . substitute(ret, '\n', '', 'g')	
endif
```
```vim
if &shell =~? 'sh$'	    " All characters must be encoded to system encoding.
let cmd = flags =~# 'r' ? 'rm -rf' : 'rmdir'	    if s:need_trans
let ret = system(cmd . ' ' . shellescape(a:path))	      let path  = iconv(path, &encoding, 'char')
else
```
I think we should decide what should do here.
* Arguments must be converted to &encoding to char? (yes, fixed)
* Need to quote with double-quote in the command? (yes, fixed)
* Need to throw …

System.File: quote file names in command arguments

---

autoload/vital/__vital__/Text/TOML.vim
test/Text/TOML.vim

Consider the following TOML file:
```
foo = """
delimiter = '\"""'
"""
```
`"""` in the second line is escaped by `\`, but an old implementation
stops parsing at here and had occurred an error.

Text.TOML: Fix an error with multiline basic string

---

autoload/vital/__vital__/Data/Set.vim
autoload/vital/__vital__/Vim/Python.vim
autoload/vital/__vital__/Vim/ScriptLocal.vim
autoload/vital/vital.vim
test/Locale/Message.vimspec

Some `:catch`s use incomplete patterns for errors.

Fix error catching

---

autoload/vital/__vital__/Data/Base64.vim

https://github.com/vim-jp/vital.vim/blob/ccc69e2a0fd3ed1fb1576b217dbc6236e1a9b018/autoload/vital/__vital__/Data/Base64.vim#L63-L68
デコードでの上記処理ですが、a:b64処理後に削っても意味がなく、意図するところとしてbytesを削るのではないでしょうか?
下記のようにして動作を確認し、正常ではあることは簡単には確認できました。
意図する所に当っているか、確認したいと思いIssueを挙げます。
```vim
if a:b64[-1] == a:pad
unlet bytes[-1]
endif
if a:b64[-2] == a:pad
unlet bytes[-1]
endif
```
RFCのBase64の
```
(1) The final quantum of encoding input is an integral multiple of 24
bits; here, the final unit of encoded output will be an integral
multiple of 4 characters with no "=" padding.
(2) The final quantum of encoding input is exactly 8 bits; here, the
final unit of encoded output will be two characters followed by
two "=" padding characters.
(3) The final quantum of encoding input is exactly 16 bits; here, the
final …
```

Data.Base64 decode miss operation?

---

autoload/vital/__vital__/Data/Base64.vim

see #639
review check point spread other module
checkk all "eval decode 16/2 base num"
---
base32レビュー時にでた指摘を水平展開します。
この修正が必要なのが他にはなさそうなので、これだけです。
1行関数みたいなのは各モジュールが自前で持ってますし、正直くくりだしが難しいですが、アップデートとDRYを考えると悩ましいですね。

Fix: Base64 base32's reviewed s:_binstr2bytes(str) check fixing

---

test/Data/Base64.vimspec

see #640
and see #641 (mistake closed)
Add RFC TestVector to Data.Base64
There is coverage improvement. (by passing the check pass in padding)
If it's a good one, Please merge it.

Data.Base64: Add testcase for RFC TestVector

---

autoload/vital/__vital__/Hash/MD5.vim
doc/vital/Hash/MD5.txt
test/Hash/MD5.vim

Currently MD5 has only sum (like md5sum).
However, there is a shortage of APIs to use as components.
Proposal:
* sum : return hash string
* digest : return hash bytes list (new, easy to use for other process)
and matrix
* x(str) : accept string data
* x_raw(bytes) : accept bytes list
after PRed this API support.
Thanks.

Proposal: Interface Extension of MD5

---

.appveyor.yml
scripts/coverage.sh

Vim 8.1.0365 よりプロファイルログに関数定義箇所が記載されるようになった。
(`Defined: /path/to/src.vim line XXX`)
covimerage はその情報を使って関数内容とソース行を対応させているが、`execute` を使って文字列評価により定義した関数では、関数内容とソース行が文字列として一致しない。
e.g. https://github.com/vim-jp/vital.vim/blob/master/autoload/vital/__vital__/Web/URI.vim#L640-L644
そのような場合に covimerage は assert で終了する。
`Defined:` の行を削除し、ログを 8.1.0365 以前のフォーマットにする。
covimerage にその辺りをうまく処理するようなオプションが欲しいところです。

Avoid covimerage error

---

scripts/coverage.sh

`osx` 環境で `covimerage` へのパスが通っていません。

Fix covimerage in osx

---

.appveyor.yml
scripts/coverage.sh

最新の covimerage (1.6~) では #651 が修正されているので workaround を削除しました。
Ref:
https://github.com/Vimjas/covimerage/issues/73
https://github.com/Vimjas/covimerage/issues/74

Remove the workaround for covimerage

---

autoload/vital/__vital__/Web/HTTP.vim
doc/vital/Web/HTTP.txt

add --unix-socket option to curl
ex:
```vim
let s:V = vital#train#new()
let s:HTTP = s:V.import('Web.HTTP')
let response = s:HTTP.request("http://localhost/images/json", {
\ 'unixSocket': '/var/run/docker.sock',
\ })
echo response.content
```

add unix socket option to curl

---

README.md
autoload/vital/__vital__/Hash/SHA1.vim
doc/vital.txt
doc/vital/Hash/SHA1.txt
test/Hash/SHA1.vim

based on [vim\-scripts/sha1\.vim: sha1\(\) function](https://github.com/vim-scripts/sha1.vim)
- support same I/F MD5
- add test
- add document
---
元にしたものがvim-scriptsオフィシャルにあること、ライセンス的にIETFのRFCのままの文面が付加されていますが...素ライセンス的にやや謎なことなど、微妙な面がありますね...
BSD/MITレベルだとは思うので、あまり問題はない、と信じたいのですが...

Contribute Hash.SHA1

---

doc/vital/Data/List.txt

https://github.com/vim-jp/vital.vim/blob/002cfe52a83253c2fb40c0a8f9d7e79146a61e7c/doc/vital/Data/List.txt#L142-L186
---
用例が関数に合っていないように思います。
[追記:filterは合ってると思いますが、mapは関数が違うと思います(Succとした場合は適切?ですが、文字列で関数記載してる箇所も合ってないと思います。)

help error: Data.List map() example do not valid sample.

---

autoload/vital/__vital__/Web/URI.vim

@tyru 
* Closes https://github.com/vim-jp/vital.vim/issues/664
* This solves all the vint violations for Web.URI
* This also helps debugging, since you can jump to the definition easily.

Web.URI: Cosmetic change to expand macro

---

autoload/vital/__vital__/Hash/MD5.vim

以下にある、上記の関数では副作用として引数を変更します。
いまのところ実害はない使い方をしていますが、実装を副作用のないものに変えたほうがいいかもしれません。
- Data.Base64 (用途違い、対策不要)
- Data.Base32 (用途違い、対策不要)
- Hash.MD5
修正案
```vim
function! s:_bytes2str(bytes) abort
return join(map(copy(a:bytes), 'printf(''%02x'', v:val)'), '')
endfunction
```

Sideeffects: s:_bytes2str(bytes) modify arg bytes

---

autoload/vital/__vital__/DateTime.vim
doc/vital/DateTime.txt
test/DateTime.vimspec

This PR is fix #658 
- check num64
- add test num64 and not num64
- document update

DateTime: support 64bit unix epoch in DateTime.unix_time()

---

autoload/vital/__vital__/Data/Base32.vim
autoload/vital/__vital__/Data/Base64.vim
doc/vital/Data/Base32.txt
doc/vital/Data/Base64.txt
test/Data/Base32.vimspec
test/Data/Base64.vimspec

Currently Base64/32 do not have byte-list from/to API.
Therefore, there is a shortage of APIs to use as components.
Proposal:
```
Bytes-list encode to BaseX
encodebytes({bytes})			
Return baseX encoded string from {bytes}.
Return decoded Bytes-list
decoderaw({str})			
Return decoded bytes-list from {str} that's baseX encoded.
```
Thanks.

Proposal: Interface Extension of Base64/Base32

---

autoload/vital/__vital__/Web/HTTP.vim

On Neovim v0.3.1 on Windows8.1, s:_quote() in Web/HTTP.vim returns ', but command line parameters must be quoted by ", not by ' on Windows.
shellescape('')[0] should return a correct quote character.

Web.HTTP: Change how to get quote character

---

autoload/vital/__vital__/Data/Base32.vim

Problem:
It did not operate in the environment which is not `num64` because the variable manipulation of size more than 4 bytes in Data.Base32
Solution:
Processing was divided and processed within 4 bytes

Data.Base32: fix encode/decode 32bit env support

---

autoload/vital/__vital__/Vim/Type.vim
doc/vital/Vim/Type.txt
test/Vim/Type.vimspec

vital.vimとしてはblob未サポート環境もまだ範囲内ですが、利用側としてはblobを使う可能性があるので、サポートを拡充したほうがよいと思います。

SupportUpdate: Vim.Type currently not map blob type

---

autoload/vital/__vital__/Validator/Args.vim
doc/vital/Validator/Args.txt
test/Validator/Args.vim

https://github.com/vim-jp/vital.vim/pull/504#issuecomment-301294962 でチラッと言ってたやつです。
> > * 不正な引数に対して型チェックをしないと無名関数やラムダが入り混じった深いスタックトレースが出て訳分からんので引数チェックする
> 
> この件は結構修正量デカくなりそうだったので別 PR へ持ち越します（汎用的な引数チェックモジュール Validator.Args を作成予定）。
関数の引数をチェックして、正しくない型や式にマッチしない値だったら例外を投げるモジュールです。

Add Validator.Args module

---

autoload/vital/__vital__/System/Filepath.vim
test/System/Filepath.vimspec

環境 Windows
ターゲットpath D:\data
pwd D:\data\test
の状態で
FIlepath.abspathに、`\Data\`を入れると `D:\Data\test\Data\`のようになる
(カレントドライブレターはfinddir他で消えることがあるので...fnamemodifyで直ることを期待した)
これは、\Data\がisdirecotryではあってもfilereadableではないためのようです。
逆に上記の状態で`\Data\`はisdirectoryで1が返ります。そして手動でfnamemodifyするとフルパスが取れます。
filereadable or isdirectoryが条件でもいいのではないか、と思うのですが、どうでしょうか?
ドキュメントにも 
> abspath({path})			*Vital.System.Filepath.abspath()*
> 	Return an absolute path of {path}.
> 	If the {path} is already an absolute path, it return the {path}.
> 	cf. |Vital.System.Filepath.relpath()|
とあり、pathであってfile、という制限ではないように読めました。
関数
```vim
function! s:abspath(path) abort
if s:is_absolute(a:path)
return a:path
endif
" Note:
"   the behavior of ':p' for non existing file path is not defined
return filereadable(a:path)
\ ? …
```

Filepath.abspath are directory' path resolving fail fix

---

autoload/vital/__vital__/Vim/Type.vim

Vim.Type have type map / type reverse map.
But it is maintained at manually.
Vim.Type type map / type reverse map generated from one typename list.
Maintenance simply.

Proposal: Vim.Type: type map/reverse map auto generate

---

autoload/vital/__vital__/Data/List.vim
doc/vital/Data/List.txt
test/Data/List.vimspec

```
count({f}, {xs})				*Vital.Data.List.count()*
NOTE: This is different to Vim script's native |count()| function.
NOTE: This is experimental. Unlike other Data.List functions, you
can't provide a string represated pseudo function to {f}.
Returns number of items in {xs} that satisfies the given predicate
function {f}.
>
echo s:L.count({ x -> x == 2 }, [1, 2, 3, 4, 5])
"=> 1
echo s:L.count({ x -> x % 2 == 0 }, [1, 2, 3, 4, 5])
"=> 2
function! s:f(x)
return a:x % 2 == 0
endfunction
echo s:L.count(function('s:f', [1, 2, 3, 4, 5])
"=> 2
<
It scans from left to right. O(n).
Non-destructive. This does not modify {xs}.
```

Add Data.List.count()

---

Changes
autoload/vital/__vital__/Prelude.vim
doc/vital/Prelude.txt

* This has been undocumented
* This function doesn't seem to be actively directly used from Vim plugins,
but only used from within Prelude
* I'd like to shrink Prelude module gradually, so let's deprecate this one for now.

Prelude: Remove escape_file_searching()

---

autoload/vital/__vital__/Prelude.vim
doc/vital/Prelude.txt
test/Prelude.vimspec

Builtin function `isinf()` is added at v8.1.1111 (vim/vim@fda1bff).
Add an equivalent function `is_infinity()` to Prelude.

Prelude: Add `is_infinity()`.

---

autoload/vital/__vital__/Validator/Args.vim
doc/vital/Validator/Args.txt
test/Validator/Args.vim

* BLOB 型をサポートしました
* Mod.TYPE は `v:t_*` 変数が使える事に気付き削除しました。 `ANY`, `OPTARG` はそれぞれ文字列で `'any'`, `'option'` のように渡すインターフェースに変更しました

Validator.Args: Support blob type, and remove Mod.TYPE constant

---

autoload/vital/__vital__/Web/HTTP.vim
doc/vital/Web/HTTP.txt

In curl
```
--oauth2-bearer <token> OAuth 2 Bearer Token
```
I'm trying to this support.

Feature request: Web.HTTP support OAuth bearer token

---

doc/vital/Data/List.txt

It's already 2020. Let's introduce Data.List for new vital users in the modern way.
This pull request does not include followings
* Any API changes such as dropping some legacy functionalities (e.g. support for old Vim with no lambda supports)
* Make the doc complete and comprehensive
But does this
* Make the doc up-to-date
* Show what we expect for Data.List and its users

Data.List: Overhaul docs to be up-to-date

---

.travis.yml
test/Async/Promise.vimspec

https://github.com/vim-jp/vital.vim/issues/698

Fix Async.Promise tests for test stabiligy even with MacVim

---

test/Async/Promise.vimspec

* I needed this to fix a flaky test, but after fixing the root cause instead,
we no longer need to specify the timeout from each test case.
* Not having many helper functions in the test increases the maintainability
* https://github.com/vim-jp/vital.vim/pull/713#discussion_r368769255
* I kept the `timeout` as a hard-coded local var instead of hard-coding into the logic as its original form,
for the ease of debug in the future. The runtime cost is ignorable.

Async.Promise: Remove test helper wait_has_key_with_timeout

---

autoload/vital/__vital__/Data/Optional.vim

I think `get_or(some(value), { -> 42 })` should not evaluate `{ -> 42 }`. Current implementation need not the default value is a function.

Data.Optional: stop evaluation of {alternative} of get_or when it has some value

---

autoload/vital/__vital__/Async/Later.vim
autoload/vital/__vital__/Async/Promise.vim
doc/vital/Async/Later.txt
test/Async/Later.vimspec

I've relied on `Async.Promise` to make [fern.vim](https://github.com/lambdalisue/fern.vim) but the performance issue occurred in Windows.
https://github.com/lambdalisue/fern.vim/pull/57
This PR introduces an event loop and workers to execute tasks. Approx. 20x performance improvement has observed in above plugin.
```vim
let s:Promise = vital#vital#import('Async.Promise')
function! s:tick() abort
let promise = s:Promise.resolve(reltime())
for i in range(1000)
let promise = promise.then({ s -> s })
endfor
return promise.then({ s -> reltimestr(reltime(s)) })
endfunction
function! s:test() abort
new
let bufnr = bufnr('%')
let promise = s:Promise.all([
\ s:tick(),
\ s:tick(),
\ s:tick(),
\ s:tick(),
\ s:tick(),
\ s:tick(),
\ s:tick(),
\ s:tick(),
\ s:tick(),
\ s:tick(),
\])
call promise.then({ …
```

Improve performance of Promise especially in Windows

---

autoload/vitalizer.vim

Git will start in the current working directory if `--work-tree` option is not given.

vitalizer: fix --hash

---

autoload/vital/vital.vim
test/Interpreter/Brainf__k.vimspec

'redir' cannnot be nested and cannot be used in execute() function.
The main reason why vital.vim used 'redir' has solved on Vim 8.0.1425 and vital.vim
now supports Vim 8.1 or later thus we can use execute() instead.
Fix #724

vitalizer: Liberate from 'redir'

---

autoload/vital/__vital__/System/Filepath.vim
doc/vital/System/Filepath.txt

The `:p` absolute path filename modifier supports leading «"~/" (and "~user/" for Unix)» for home directories. As a home-relative path like `~` does not resolve properly with filereadable() or isdirectory() (unless there's a subdirectory named `~` in the current working directory! 😅), we need to expand it ourselves.
Note that the docs say just `~/` is changed, but `~` works just as well.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vim-jp/vital.vim/722)

System.Filepath: Introduce expand_home() function

---

autoload/vital/__vital__/Async/Promise.vim
doc/vital/Async/Promise.txt
test/Async/Promise.vimspec

This PR aims to able to catch all unhandled rejection on Async.Promise.
It will be useful for logging plugin's errors, I think.

Add Promise.on_unhandled_rejection

---

autoload/vital/__vital__/Async/Promise.vim

Fixes #733
@tsuyoshicho 見つけてくださってありがとうございます。
手元でも下記のコードでエラーが発生するのが再現できました。
```viml
let Promise = vital#plugin_name#import('Async.Promise')
call Promise.on_unhandled_rejection(Promise.noop)
call Promise.new({ resolve -> execute('throw "error"') })
```
修正方法としては、noop は可変長引数を受け付けるものとし、引数の個数は無視することとしました。
テストケースに関しては、timer 中に発生してキャッチできていない例外に関してのテストは書けないのではないだろうか...？と考えています。
なにかテスト記述するいい方法がある場合はご指摘いただければ PR を更新いたします。

Fix throws error on on_unhandled_rejection

---

autoload/vital/__vital__/Web/HTTP.vim

`{endmarker}` cannot start with a lower case character.

Web.HTTP: Fix endmarker

---

autoload/vital/__vital__/Web/HTTP.vim
doc/vital/Web/HTTP.txt

Python3でのclientを実装しました。
(ただ、Pythonに詳しくないので、自信があまりありません orz)
動作自体は確認できているのですが...
テスト用コード片
```vim
let HTTP = g:V.import('Web.HTTP')
let url = 'https://www.google.com'
let res = HTTP.request('GET', url, {
\ 'client'      : ['curl'],
\})
echo res
```
```vim
let HTTP = g:V.import('Web.HTTP')
let url = 'https://www.google.com'
let res = HTTP.request('GET', url, {
\ 'client'      : ['wget'],
\})
echo res
```
```vim
let HTTP = g:V.import('Web.HTTP')
let url = 'https://www.google.com'
let res = HTTP.request('GET', url, {
\ 'client'      : ['python'],
\})
echo res
```
```vim
let HTTP = g:V.import('Web.HTTP')
let url = 'https://www.google.com'
let res = HTTP.request('GET', url, {
\ 'client'      : ['python2'],
\})
echo res
```
```vim
let HTTP = g:V.import('Web.HTTP')
let url = …
```

Web.HTTP: Python3 and 2 support(3 as high priority)

---

Changes
autoload/vital/__vital__/Web/HTTP.vim

Fix python3 filter gen list.
and changes modify.
---
#703 のマージした状態で、他プラグイン( https://github.com/y0za/vim-reading-vimrc )にPRを作成しようとして気付きました。
変更の考慮が不足していたようです。
Python3では2とは違い、filterがlistを返さないので、問題がありました。[1](https://it-engineer-lab.com/archives/124)
この修正と、あわせてChangesを準備しています。
以下のテスト確認していましたが、www.google.com だと問題なかったようで...
上記プラグインが使うvimrc readingのjsonで発生、修正もそれで確認しました。
```vim
let HTTP = g:V.import('Web.HTTP')
" let url = 'https://www.google.com'
let url = 'http://vim-jp.org/reading-vimrc/json/next.json'
let res = HTTP.request('GET', url, {
\ 'client'      : ['python'],
\})
echo res
```
vital.vim の HEAD で通信NGとなってしまうので、お手数ですが早めの確認をおねがいしたいです。

fix: http python3 fliter not list

---

autoload/vitalizer.vim
test/.themisrc
test/_testdata/vital/datatest/autoload/vital/__latest__/DataTest.txt
test/_testdata/vital/datatest/autoload/vital/__latest__/DataTest.vim
test/vital.vimspec

vitalのdependsの仕様として、データファイルを入れれますが、それを無条件でmoduleとしての処理に流していました。
モジュール名生成でミスした場合(=モジュールでないもの)はautoloadable処理をスキップするようにして対処しました。

fix: Vitalizer non-module files do not process need at s:autoloadablize

---

test/Deprecated/Text/Sexp.vim

Because error throws in the before block when `has('lua') == 0`.

Deprecated.Text.Sexp: skip the before block in test

---

autoload/vital/__vital__/Web/JSON.vim
test/Web/JSON.vimspec

This is part of #695, only bug fixes.
* Encode all control chars.
* Prev: only `\r`, `\n` and `\t` are converted.
* Fixed: all of `\x01` to `\x1f` are converted.
* Decode UTF-16 surrogate pairs.
* Prev: can not decoded.
* Fixed: can decoded.

Web.JSON: fix char encodes

---

autoload/vital/vital.vim
test/_testdata/vital/testplugin/autoload/vital/__testplugin__/ErrorSelfmodule.vim
test/vital.vimspec

Vital shows stacktrace, when error throws in `module._vital_loaded()`.
But the stacktrace formatter function has bugs.
* If anonymous or lambda function exists in stack, an error occurs in the formatter.
* Function attributes are not detected.
... and minor fixes.

vital: fix import error handling

---

autoload/vital/__vital__/Deprecated/Text/Sexp.vim

Fix lua index base diff.
Fix or remove? (It is deprecated group).

Deprecated.Text.Sexp: fix Lua array index base in 8.2.1066 0 to 1

---

autoload/vital/__vital__/Web/HTTP.vim
autoload/vital/__vital__/Web/HTTP_python2.py
autoload/vital/__vital__/Web/HTTP_python3.py

#730 で付属ファイルが安定して扱えるようになったので、Web.HTTPでpythonコードを.pyに分離する提案です。
確認コード
```vim
let HTTP = g:V.import('Web.HTTP')
let url = 'http://vim-jp.org/reading-vimrc/json/next.json'
let res = HTTP.request('GET', url, { 'client' : ['python']})
echo res
```
また、プラグインとして導入して問題ないことも確認しています。
---
メンテナンス性のためなので、どう扱うかは協議してになるかな、と考えています。
(ファイル名とかかなりやっつけ感はあるので微妙ですが...)

Suggestion: separation of python code for Web.HTTP

---

autoload/vital/__vital__/Async/Promise.vim
doc/vital/Async/Promise.txt
test/Async/Promise.vimspec

Vim does not have async/await syntax support thus it's a bit tough work
to write similar function as below (js)
```js
for (const url of urls) {
const r = await request(url);
console.log(r)
}
```
With this commit, equivalent code of above can be written as
```vim
let fs = map(urls, { url -> { -> request(url).then({ r -> execute('echo r', '') }) })
call s:Promise.chain(fs)
```
**Question:** Is there any way to avoid stack-overflow or should I comment on the doc?

Async.Promise: Add "chain" function

---

test/Async/Later.vimspec
test/vital.vimspec

Detect test broken
see
https://travis-ci.org/github/vim-jp/vital.vim/jobs/715004455
- Async.Later .call() echomsg an exception when a task throws an exception
> Hello World
> VimEnter Autocommands for "*"..function <SNR>1_main[9]..<SNR>1_start[14]..themis#command#start[10]..themis#run[4]..11[23]..15[6]..16[2]..17[7]..17[7]..17[7]..17[5]..18[3]..19[5]..111[1]..2435[10]..<SNR>151__worker[12]..<lambda>4137[1]..<SNR>107_throw, line 1'
- vital vital-Vital-object .import can handle error stack in s:_vital_loaded(V)
>          expected exception: '^vital: fail to call \._vital_loaded(): FOO from:\_.*\nfunction \S*_vital_loaded(\.\.\.) abort Line:\d\+ (.*\/ErrorSelfmodule\.vim\( Line:\d\+\)\?)\nfunction <lambda>\d\+(\.\.\.) Line:\d\+ (.*\/ErrorSelfmodule\.vim\( Line:\d\+\)\?)\nfunction …

fix: broken test for latest vim.

---

autoload/vital/__vital__/Async/Promise.vim

Without l: prefix, "E705: Variable name conflicts with existing function" will be thrown if user defines same name global function.
```vim
let s:root = fnamemodify(expand('<sfile>'), ':p:h')
execute printf('set runtimepath+=%s', fnameescape(s:root))
let s:Promise = vital#vital#import('Async.Promise')
function! Factory(a, b, c) abort
endfunction
call s:Promise.chain([{ -> s:Promise.resolve() }])
```
```
function <SNR>316_chain[1]..<SNR>316__chain, line 4
E705: Variable name conflicts with existing function: Factory
```
```
```

Async.Promise: Add l: prefix to variable for funcref

---

Changes
autoload/vital/__vital__/System/Process/Vimproc.vim
test/System/Process/Vimproc.vimspec

```
vimproc#system({expr} [, {input} [, {timeout}]])	*vimproc#system()*
(...)
If you set {timeout}, vimproc will kill the process after
{timeout} and throw "vimproc: vimproc#system(): Timeout."
exception.
The unit is millisecond.
```
timeout unit as millisecond.
```
*Vital.System.Process.execute()*
execute({args}[, {options}])
(...)
The following attributes are supported in {options}
(...)
"timeout"
A process timeout in seconds (|Number|). A system process
client does not support this option, mean that vimproc is
required to be available.
Default: 0
```
timeout unit as second.
https://github.com/vim-jp/vital.vim/blob/1b9fab508176efd8bc3fcbc435afd8d7b928ef53/autoload/vital/__vital__/System/Process/Vimproc.vim#L37-L70
call `vimproc#system()` with options.timeout directly.
use second value …

System.Process.Vimproc: fix timeout unit

---

autoload/vital/__vital__/System/Filepath.vim
test/System/Filepath.vimspec

rel https://github.com/lambdalisue/fern.vim/issues/226
(And I used it as a base for the correction code)
`shellslash` not care in vital.vim.
But `completeslash` option affect  to only `expand()` result  and  non controled.
This PR is fix it.

fix: System.Filepath.expand_home() fix for completeslash

---

autoload/vital/__vital__/Web/HTTP_python2.py
autoload/vital/__vital__/Web/HTTP_python3.py

close #760 
This PR include below fix:
- Web.HTTP Python3 client handle ContentTooShortError
- Web.HTTP Python3 client check res is `None`
(https://docs.python.org/ja/3/library/urllib.request.html#urllib.request.urlopen urlopen may return `None`)
And more
- add HTTPError object handling
- same fix in Python2

fix: Web.HTTP: python3 client fix unhandled error to handle

---

doc/vital/Data/List.txt
test/Data/List.vimspec
test/DateTime.vimspec

* This is not a breaking change.
* This pull request does not change all the existing Data.List tests/documents, but works fine and documentation still makes sense.
* I'm planning to keep working on the rest gradually.
* Next steps after this pull request:
* Make sure all the tests and docs at Data.List follow the new rule
* Output warning message when Vim plugins use the old way, but
still keeps the behaviour (CHANGELOG needed)
* Remove old behaviour after a long time (CHANGELOG needed)

Data.List: Gradually deprecate old String representation of lambda

---

autoload/vital/__vital__/Data/String/Interpolation.vim
test/Data/String/Interpolation.vimspec

Vim [8.2.2948](https://github.com/vim/vim/commit/7a2217bedd223df4c8bbebe731bf0b5fe8532533)
による修正で、floatの文字列結合挙動が変りました。
Data.String.Interpolationに影響がありましたので、修正を作成しました。
ただ、アドホックな面があるので、これが最適かについてはレビューにて調整できたらと考えます。
Travis CIはクレジット不足のはずですので、手元でGHAで実行した結果がありますので添付します。
https://github.com/tsuyoshicho/vital.vim/actions/runs/1010662757
(Windows latestの別問題はとりあえず置いておくとして)
参考 NG時
https://github.com/tsuyoshicho/vital.vim/runs/3015278186?check_suite_focus=true

Data.String.Interpolation: fix float handling after 8.2.2948

---

.github/workflows/reviewdog.yml

Fis is error
https://github.com/vim-jp/vital.vim/runs/3157022032
English is valid, but current misspell setting "US" detect "UK" type miss spell.
This project accept US/UK, change setting.

ci: misspell use both US/UK

---

autoload/vital/__vital__/Color.vim
test/Color.vim

This PR is fix Color class error
see current test result(themis auto update PR test)
https://github.com/vim-jp/vital.vim/pull/778

Color: fix v:colorname support

---

test/Data/Closure.vimspec

Fix latest Windows/mac test failure.
In latest Vim,  exception raise E1085 instead E117 in Data.Closure's "target function check after gc" test .
NOTE: But, kept E117 in linux.
---
E1085 の情報がなく、このエラーが発生することが意図する所なのか、想定外が出ているのかが明確ではありません。
ただ利用側から見て、利用不可能になったfuncrefとしてこのエラーとなっているようなので、対応しました。
```vim
let F = {-> 'echo'}
echo string(F)
let F = v:null
call F()
```
```
|| 
|| function('<lambda>47042')
|| function quickrun#command#execute[10]..quickrun#run[10]..548[10]..543[3]..<SNR>775_execute[9]..script C:\Users\tsuyoshi\AppData\Local\Temp\V008BC1.tmp, 行 4
|| E1085: Not a callable type: F
```
in Vim
```
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Dec 22 2021 21:36:41)
MS-Windows 64 ビット GUI/コンソール 版 with OLE サポート
適用済パッチ: 1-3875
```

Data.Closure: fix test in latest Windows/mac exception error E1085

---

.github/workflows/buildtest.yml

Replace `git clone` by using `actions/checkout` to organize steps.

ci: Organize buildtest workflow

---

requirements.txt

requirements update
History
1. covimerage==0.2.1 only
2. add click<8.0.0 see issue https://github.com/Vimjas/covimerage/issues/95
3. now fix click ver. 8 / latest https://github.com/Vimjas/covimerage/pull/97

ci: fix requiremnets (click 8.0.0 limit Already unnecessary)

---

.github/actions/vital-throw-message/Dockerfile

他のリポジトリで renovate より更新があったので展開。
影響はよくもわるくも無いので、折を見て更新でよいかと。

Update golang image for action

---

test/Async/Promise.vimspec

Close #809 
Update Async.Promise .wait test:
* Split test: resolved pattern and rejected pattern
* Update test timing pattern: complete 500 and 700
* Update assert : lower limit and upper limmit
---
他のテストとの兼ね合いはありそうですが、現在わかってる範囲で改善を行いました。
全体としてもうすこし細かく確認を分割したほうがいい気はしますね。
macについては、アンダーフロー、オーバーフローのどちらも出たので、精度的な問題として暫定で範囲を広げて対応しています。
ここを見そうな方を暫定でreviewer指定しています

fix: Update tests for Async.Promise .wait

---

.github/workflows/buildtest.yml

* pip の更新で `error: externally-managed-environment` が発生する問題に `--break-system-packages` を指定することで対処。(venv を使う方がよいかもしれない。)
* 最新の macOS では Vim v8.2.1310 以降しかビルドできなくなってしまったので、v8.2.0020 をスキップ。

CI: Work around macOS errors

---

.github/workflows/depup.yml

CI jobs for depup were not automatically executed because we used GITHUB_TOKEN.
To work around the restriction of GITHUB_TOKEN, use action/create-github-app-token to generate a token.
See:
* https://zenn.dev/suzutan/articles/how-to-use-github-apps-token-in-github-actions
* https://docs.github.com/en/issues/planning-and-tracking-with-projects/automating-your-project/automating-projects-using-actions
* https://github.com/marketplace/actions/create-github-app-token
* https://github.com/vim-jp/vimdoc-ja-working/pull/1598

Use vim-jp bot app when running depup

---

.github/workflows/buildtest.yml

Windowsでのlua dllダウンロードエラーを修正します
- CI でのダウンロードを [WebClient](https://learn.microsoft.com/ja-jp/dotnet/api/system.net.webclient) から [Invoke-WebRequest](https://learn.microsoft.com/ja-jp/powershell/module/microsoft.powershell.utility/invoke-webrequest) に変更、あわせて UserAgentを明記
- > WebRequest、HttpWebRequest、ServicePoint、WebClient は廃止されており、新しい開発には使用しないでください。 代わりに [HttpClient](https://learn.microsoft.com/ja-jp/dotnet/api/system.net.http.httpclient?view=net-9.0) を使用してください。
- [ここ](https://stackoverflow.com/questions/69386094/error-403-when-trying-to-access-url-able-to-access-through-browser-without-erro)にあるように UserAgent 指定がないとエラーが出やすいみたいなので
- 今回の動作のエラーも、UserAgent指定がないことが由来と思われます
CIを参照

ci: fix windows download method

---

test/Data/Base16.vimspec

Base16 のテストにミスがあったので修正しています。
単純な hex string の扱いの部分のため、test vector が不足しているので補填していたのですが、
補填時にミスっていました。
---
現在Windowsは別問題でNGになります

Data.Base16: fix encode test vector
